/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package org.reso.commander;

import org.junit.Test;

public class AppTest {
    @Test public void testParameterDeserialization() {
        //TODO
    }
}
