# This file was autogenerated on: 20230403153708907
Feature: MemberStateLicenses

  Background:
    Given a RESOScript or Metadata file are provided
    When a RESOScript file is provided
    Then Client Settings and Parameters can be read from the RESOScript
    And a test container was successfully created from the given RESOScript file
    And the test container uses an Authorization Code or Client Credentials for authentication
    And valid metadata were retrieved from the server
    When a metadata file is provided
    Then a test container was successfully created from the given metadata file
    And valid metadata are loaded into the test container

  @MemberStateLicenses @dd-2.0
  Scenario: MemberMlsId
    When "MemberMlsId" exists in the "MemberStateLicenses" metadata
    Then "MemberMlsId" MUST be "String" data type
    And "MemberMlsId" length SHOULD be equal to the RESO Suggested Max Length of 25

  @MemberStateLicenses @dd-2.0
  Scenario: MemberKey
    When "MemberKey" exists in the "MemberStateLicenses" metadata
    Then "MemberKey" MUST be "String" data type
    And "MemberKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @MemberStateLicenses @dd-2.0
  Scenario: MemberStateLicense
    When "MemberStateLicense" exists in the "MemberStateLicenses" metadata
    Then "MemberStateLicense" MUST be "String" data type
    And "MemberStateLicense" length SHOULD be equal to the RESO Suggested Max Length of 50

  @MemberStateLicenses @dd-2.0
  Scenario: MemberStateLicenseExpirationDate
    When "MemberStateLicenseExpirationDate" exists in the "MemberStateLicenses" metadata
    Then "MemberStateLicenseExpirationDate" MUST be "Date" data type

  @MemberStateLicenses @dd-2.0
  Scenario: MemberStateLicenseType
    When "MemberStateLicenseType" exists in the "MemberStateLicenses" metadata
    Then "MemberStateLicenseType" MUST be "Single Enumeration" data type

  @MemberStateLicenses @dd-2.0
  Scenario: MemberStateLicenseState
    When "MemberStateLicenseState" exists in the "MemberStateLicenses" metadata
    Then "MemberStateLicenseState" MUST be "Single Enumeration" data type

  @MemberStateLicenses @dd-2.0
  Scenario: ModificationTimestamp
    When "ModificationTimestamp" exists in the "MemberStateLicenses" metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type

  @MemberStateLicenses @dd-2.0
  Scenario: MemberStateLicenseKey
    When "MemberStateLicenseKey" exists in the "MemberStateLicenses" metadata
    Then "MemberStateLicenseKey" MUST be "String" data type
    And "MemberStateLicenseKey" length SHOULD be equal to the RESO Suggested Max Length of 255
