# This file was autogenerated on: 20200929220925944
Feature: ContactListingNotes

  Background:
    Given a RESOScript or Metadata file are provided
    When a RESOScript file is provided
    Then Client Settings and Parameters can be read from the RESOScript
    And a test container was successfully created from the given RESOScript file
    And the test container uses an Authorization Code or Client Credentials for authentication
    And valid metadata were retrieved from the server
    When a metadata file is provided
    Then a test container was successfully created from the given metadata file
    And valid metadata are loaded into the test container

  @ContactKey @ContactListingNotes
  Scenario: ContactKey
    When "ContactKey" exists in the "ContactListingNotes" metadata
    Then "ContactKey" MUST be "String" data type
    And "ContactKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ContactKeyNumeric @ContactListingNotes
  Scenario: ContactKeyNumeric
    When "ContactKeyNumeric" exists in the "ContactListingNotes" metadata
    Then "ContactKeyNumeric" MUST be "Integer" data type

  @ContactListingNotesKey @ContactListingNotes
  Scenario: ContactListingNotesKey
    When "ContactListingNotesKey" exists in the "ContactListingNotes" metadata
    Then "ContactListingNotesKey" MUST be "String" data type
    And "ContactListingNotesKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ContactListingNotesKeyNumeric @ContactListingNotes
  Scenario: ContactListingNotesKeyNumeric
    When "ContactListingNotesKeyNumeric" exists in the "ContactListingNotes" metadata
    Then "ContactListingNotesKeyNumeric" MUST be "Integer" data type

  @ListingId @ContactListingNotes
  Scenario: ListingId
    When "ListingId" exists in the "ContactListingNotes" metadata
    Then "ListingId" MUST be "String" data type
    And "ListingId" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ListingKey @ContactListingNotes
  Scenario: ListingKey
    When "ListingKey" exists in the "ContactListingNotes" metadata
    Then "ListingKey" MUST be "String" data type
    And "ListingKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ListingKeyNumeric @ContactListingNotes
  Scenario: ListingKeyNumeric
    When "ListingKeyNumeric" exists in the "ContactListingNotes" metadata
    Then "ListingKeyNumeric" MUST be "Integer" data type

  @ModificationTimestamp @ContactListingNotes
  Scenario: ModificationTimestamp
    When "ModificationTimestamp" exists in the "ContactListingNotes" metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type

  @NoteContents @ContactListingNotes
  Scenario: NoteContents
    When "NoteContents" exists in the "ContactListingNotes" metadata
    Then "NoteContents" MUST be "String" data type
    And "NoteContents" length SHOULD be less than or equal to the RESO Suggested Max Length of 500

  @NotedBy @ContactListingNotes
  Scenario: NotedBy
    When "NotedBy" exists in the "ContactListingNotes" metadata
    Then "NotedBy" MUST be "Single Enumeration" data type
