# This file was autogenerated on: 20200619130611893
Feature: ContactListings

  Background:
    Given a RESOScript file was provided
    And Client Settings and Parameters were read from the file
    And a test container was successfully created from the given RESOScript
    And the test container uses an Authorization Code or Client Credentials for authentication
    And valid metadata were retrieved from the server

  @AgentNotesUnreadYN @ContactListings
  Scenario: AgentNotesUnreadYN
    When "AgentNotesUnreadYN" exists in the "ContactListings" metadata
    Then "AgentNotesUnreadYN" MUST be "Boolean" data type

  @ClassName @ContactListings
  Scenario: ClassName
    When "ClassName" exists in the "ContactListings" metadata
    Then "ClassName" MUST be "Single Enumeration" data type

  @ContactKey @ContactListings
  Scenario: ContactKey
    When "ContactKey" exists in the "ContactListings" metadata
    Then "ContactKey" MUST be "String" data type
    And "ContactKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ContactKeyNumeric @ContactListings
  Scenario: ContactKeyNumeric
    When "ContactKeyNumeric" exists in the "ContactListings" metadata
    Then "ContactKeyNumeric" MUST be "Integer" data type

  @ContactListingPreference @ContactListings
  Scenario: ContactListingPreference
    When "ContactListingPreference" exists in the "ContactListings" metadata
    Then "ContactListingPreference" MUST be "Single Enumeration" data type

  @ContactListingsKey @ContactListings
  Scenario: ContactListingsKey
    When "ContactListingsKey" exists in the "ContactListings" metadata
    Then "ContactListingsKey" MUST be "String" data type
    And "ContactListingsKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ContactListingsKeyNumeric @ContactListings
  Scenario: ContactListingsKeyNumeric
    When "ContactListingsKeyNumeric" exists in the "ContactListings" metadata
    Then "ContactListingsKeyNumeric" MUST be "Integer" data type

  @ContactLoginId @ContactListings
  Scenario: ContactLoginId
    When "ContactLoginId" exists in the "ContactListings" metadata
    Then "ContactLoginId" MUST be "String" data type
    And "ContactLoginId" length SHOULD be less than or equal to the RESO Suggested Max Length of 25

  @ContactNotesUnreadYN @ContactListings
  Scenario: ContactNotesUnreadYN
    When "ContactNotesUnreadYN" exists in the "ContactListings" metadata
    Then "ContactNotesUnreadYN" MUST be "Boolean" data type

  @DirectEmailYN @ContactListings
  Scenario: DirectEmailYN
    When "DirectEmailYN" exists in the "ContactListings" metadata
    Then "DirectEmailYN" MUST be "Boolean" data type

  @LastAgentNoteTimestamp @ContactListings
  Scenario: LastAgentNoteTimestamp
    When "LastAgentNoteTimestamp" exists in the "ContactListings" metadata
    Then "LastAgentNoteTimestamp" MUST be "Timestamp" data type

  @LastContactNoteTimestamp @ContactListings
  Scenario: LastContactNoteTimestamp
    When "LastContactNoteTimestamp" exists in the "ContactListings" metadata
    Then "LastContactNoteTimestamp" MUST be "Timestamp" data type

  @ListingId @ContactListings
  Scenario: ListingId
    When "ListingId" exists in the "ContactListings" metadata
    Then "ListingId" MUST be "String" data type
    And "ListingId" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ListingKey @ContactListings
  Scenario: ListingKey
    When "ListingKey" exists in the "ContactListings" metadata
    Then "ListingKey" MUST be "String" data type
    And "ListingKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ListingKeyNumeric @ContactListings
  Scenario: ListingKeyNumeric
    When "ListingKeyNumeric" exists in the "ContactListings" metadata
    Then "ListingKeyNumeric" MUST be "Integer" data type

  @ListingModificationTimestamp @ContactListings
  Scenario: ListingModificationTimestamp
    When "ListingModificationTimestamp" exists in the "ContactListings" metadata
    Then "ListingModificationTimestamp" MUST be "Timestamp" data type

  @ListingSentTimestamp @ContactListings
  Scenario: ListingSentTimestamp
    When "ListingSentTimestamp" exists in the "ContactListings" metadata
    Then "ListingSentTimestamp" MUST be "Timestamp" data type

  @ListingViewedYN @ContactListings
  Scenario: ListingViewedYN
    When "ListingViewedYN" exists in the "ContactListings" metadata
    Then "ListingViewedYN" MUST be "Boolean" data type

  @ModificationTimestamp @ContactListings
  Scenario: ModificationTimestamp
    When "ModificationTimestamp" exists in the "ContactListings" metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type

  @PortalLastVisitedTimestamp @ContactListings
  Scenario: PortalLastVisitedTimestamp
    When "PortalLastVisitedTimestamp" exists in the "ContactListings" metadata
    Then "PortalLastVisitedTimestamp" MUST be "Timestamp" data type

  @ResourceName @ContactListings
  Scenario: ResourceName
    When "ResourceName" exists in the "ContactListings" metadata
    Then "ResourceName" MUST be "Single Enumeration" data type
