# This file was autogenerated on: 20200415150423335
Feature: ContactListingNotes

  @ContactKey
  Scenario: ContactKey
    Given "ContactKey" exists in the metadata
    Then "ContactKey" MUST be "String" data type
    And "ContactKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @ContactKeyNumeric
  Scenario: ContactKeyNumeric
    Given "ContactKeyNumeric" exists in the metadata
    Then "ContactKeyNumeric" MUST be "Integer" data type

  @ContactListingNotesKey
  Scenario: ContactListingNotesKey
    Given "ContactListingNotesKey" exists in the metadata
    Then "ContactListingNotesKey" MUST be "String" data type
    And "ContactListingNotesKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @ContactListingNotesKeyNumeric
  Scenario: ContactListingNotesKeyNumeric
    Given "ContactListingNotesKeyNumeric" exists in the metadata
    Then "ContactListingNotesKeyNumeric" MUST be "Integer" data type

  @ListingId
  Scenario: ListingId
    Given "ListingId" exists in the metadata
    Then "ListingId" MUST be "String" data type
    And "ListingId" length should be less than or equal to the RESO Suggested Max Length of 255

  @ListingKey
  Scenario: ListingKey
    Given "ListingKey" exists in the metadata
    Then "ListingKey" MUST be "String" data type
    And "ListingKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @ListingKeyNumeric
  Scenario: ListingKeyNumeric
    Given "ListingKeyNumeric" exists in the metadata
    Then "ListingKeyNumeric" MUST be "Integer" data type

  @ModificationTimestamp
  Scenario: ModificationTimestamp
    Given "ModificationTimestamp" exists in the metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type
    And "ModificationTimestamp" length should be less than or equal to the RESO Suggested Max Length of 27

  @NoteContents
  Scenario: NoteContents
    Given "NoteContents" exists in the metadata
    Then "NoteContents" MUST be "String" data type
    And "NoteContents" length should be less than or equal to the RESO Suggested Max Length of 500

  @NotedBy
  Scenario: NotedBy
    Given "NotedBy" exists in the metadata
    And "NotedBy" enum values exist in the metadata
    And "NotedBy" enum types MUST have at least one member
    Then "NotedBy" MUST be "String" data type
    And "NotedBy" should only contain enum values found in the metadata
    And "NotedBy" enumerations must match  MUST have annotations if they contain special characters
    And "NotedBy" length should be less than or equal to the RESO Suggested Max Length of 25
