# This file was autogenerated on: 20200415150423335
Feature: HistoryTransactional

  @ChangeType
  Scenario: ChangeType
    Given "ChangeType" exists in the metadata
    And "ChangeType" enum values exist in the metadata
    And "ChangeType" enum types MUST have at least one member
    Then "ChangeType" MUST be "String" data type
    And "ChangeType" should only contain enum values found in the metadata
    And "ChangeType" enumerations must match  MUST have annotations if they contain special characters
    And "ChangeType" length should be less than or equal to the RESO Suggested Max Length of 255

  @ChangedByMemberID
  Scenario: ChangedByMemberID
    Given "ChangedByMemberID" exists in the metadata
    Then "ChangedByMemberID" MUST be "String" data type
    And "ChangedByMemberID" length should be less than or equal to the RESO Suggested Max Length of 25

  @ChangedByMemberKey
  Scenario: ChangedByMemberKey
    Given "ChangedByMemberKey" exists in the metadata
    Then "ChangedByMemberKey" MUST be "String" data type
    And "ChangedByMemberKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @ChangedByMemberKeyNumeric
  Scenario: ChangedByMemberKeyNumeric
    Given "ChangedByMemberKeyNumeric" exists in the metadata
    Then "ChangedByMemberKeyNumeric" MUST be "Integer" data type

  @ClassName
  Scenario: ClassName
    Given "ClassName" exists in the metadata
    Then "ClassName" MUST be "String" data type
    And "ClassName" length should be less than or equal to the RESO Suggested Max Length of 255

  @FieldKey
  Scenario: FieldKey
    Given "FieldKey" exists in the metadata
    Then "FieldKey" MUST be "String" data type
    And "FieldKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @FieldKeyNumeric
  Scenario: FieldKeyNumeric
    Given "FieldKeyNumeric" exists in the metadata
    Then "FieldKeyNumeric" MUST be "Integer" data type

  @FieldName
  Scenario: FieldName
    Given "FieldName" exists in the metadata
    Then "FieldName" MUST be "String" data type
    And "FieldName" length should be less than or equal to the RESO Suggested Max Length of 255

  @HistoryTransactionalKey
  Scenario: HistoryTransactionalKey
    Given "HistoryTransactionalKey" exists in the metadata
    Then "HistoryTransactionalKey" MUST be "String" data type
    And "HistoryTransactionalKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @HistoryTransactionalKeyNumeric
  Scenario: HistoryTransactionalKeyNumeric
    Given "HistoryTransactionalKeyNumeric" exists in the metadata
    Then "HistoryTransactionalKeyNumeric" MUST be "Integer" data type

  @ModificationTimestamp
  Scenario: ModificationTimestamp
    Given "ModificationTimestamp" exists in the metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type
    And "ModificationTimestamp" length should be less than or equal to the RESO Suggested Max Length of 27

  @NewValue
  Scenario: NewValue
    Given "NewValue" exists in the metadata
    Then "NewValue" MUST be "String" data type
    And "NewValue" length should be less than or equal to the RESO Suggested Max Length of 8000

  @OriginatingSystemHistoryKey
  Scenario: OriginatingSystemHistoryKey
    Given "OriginatingSystemHistoryKey" exists in the metadata
    Then "OriginatingSystemHistoryKey" MUST be "String" data type
    And "OriginatingSystemHistoryKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @OriginatingSystemID
  Scenario: OriginatingSystemID
    Given "OriginatingSystemID" exists in the metadata
    Then "OriginatingSystemID" MUST be "String" data type
    And "OriginatingSystemID" length should be less than or equal to the RESO Suggested Max Length of 25

  @OriginatingSystemName
  Scenario: OriginatingSystemName
    Given "OriginatingSystemName" exists in the metadata
    Then "OriginatingSystemName" MUST be "String" data type
    And "OriginatingSystemName" length should be less than or equal to the RESO Suggested Max Length of 255

  @PreviousValue
  Scenario: PreviousValue
    Given "PreviousValue" exists in the metadata
    Then "PreviousValue" MUST be "String" data type
    And "PreviousValue" length should be less than or equal to the RESO Suggested Max Length of 8000

  @ResourceName
  Scenario: ResourceName
    Given "ResourceName" exists in the metadata
    Then "ResourceName" MUST be "String" data type
    And "ResourceName" length should be less than or equal to the RESO Suggested Max Length of 255

  @ResourceRecordID
  Scenario: ResourceRecordID
    Given "ResourceRecordID" exists in the metadata
    Then "ResourceRecordID" MUST be "String" data type
    And "ResourceRecordID" length should be less than or equal to the RESO Suggested Max Length of 255

  @ResourceRecordKey
  Scenario: ResourceRecordKey
    Given "ResourceRecordKey" exists in the metadata
    Then "ResourceRecordKey" MUST be "String" data type
    And "ResourceRecordKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @ResourceRecordKeyNumeric
  Scenario: ResourceRecordKeyNumeric
    Given "ResourceRecordKeyNumeric" exists in the metadata
    Then "ResourceRecordKeyNumeric" MUST be "Integer" data type

  @SourceSystemHistoryKey
  Scenario: SourceSystemHistoryKey
    Given "SourceSystemHistoryKey" exists in the metadata
    Then "SourceSystemHistoryKey" MUST be "String" data type
    And "SourceSystemHistoryKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @SourceSystemID
  Scenario: SourceSystemID
    Given "SourceSystemID" exists in the metadata
    Then "SourceSystemID" MUST be "String" data type
    And "SourceSystemID" length should be less than or equal to the RESO Suggested Max Length of 25

  @SourceSystemName
  Scenario: SourceSystemName
    Given "SourceSystemName" exists in the metadata
    Then "SourceSystemName" MUST be "String" data type
    And "SourceSystemName" length should be less than or equal to the RESO Suggested Max Length of 255
