# This file was autogenerated on: 202006161106009
Feature: Media

  Background:
    Given a RESOScript file was provided
    And Client Settings and Parameters were read from the file
    And a test container was successfully created from the given RESOScript
    And the test container uses an Authorization Code or Client Credentials for authentication
    And valid metadata were retrieved from the server

  @ChangedByMemberID @Media
  Scenario: ChangedByMemberID
    When "ChangedByMemberID" exists in the "Media" metadata
    Then "ChangedByMemberID" MUST be "String" data type
    And "ChangedByMemberID" length SHOULD be less than or equal to the RESO Suggested Max Length of 25

  @ChangedByMemberKey @Media
  Scenario: ChangedByMemberKey
    When "ChangedByMemberKey" exists in the "Media" metadata
    Then "ChangedByMemberKey" MUST be "String" data type
    And "ChangedByMemberKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ChangedByMemberKeyNumeric @Media
  Scenario: ChangedByMemberKeyNumeric
    When "ChangedByMemberKeyNumeric" exists in the "Media" metadata
    Then "ChangedByMemberKeyNumeric" MUST be "Integer" data type

  @ClassName @Media
  Scenario: ClassName
    When "ClassName" exists in the "Media" metadata
    Then "ClassName" MUST be "Single Enumeration" data type

  @ImageHeight @Media
  Scenario: ImageHeight
    When "ImageHeight" exists in the "Media" metadata
    Then "ImageHeight" MUST be "Integer" data type

  @ImageOf @Media
  Scenario: ImageOf
    When "ImageOf" exists in the "Media" metadata
    Then "ImageOf" MUST be "Single Enumeration" data type

  @ImageSizeDescription @Media
  Scenario: ImageSizeDescription
    When "ImageSizeDescription" exists in the "Media" metadata
    Then "ImageSizeDescription" MUST be "Single Enumeration" data type

  @ImageWidth @Media
  Scenario: ImageWidth
    When "ImageWidth" exists in the "Media" metadata
    Then "ImageWidth" MUST be "Integer" data type

  @LongDescription @Media
  Scenario: LongDescription
    When "LongDescription" exists in the "Media" metadata
    Then "LongDescription" MUST be "String" data type
    And "LongDescription" length SHOULD be less than or equal to the RESO Suggested Max Length of 1024

  @MediaCategory @Media
  Scenario: MediaCategory
    When "MediaCategory" exists in the "Media" metadata
    Then "MediaCategory" MUST be "Single Enumeration" data type

  @MediaHTML @Media
  Scenario: MediaHTML
    When "MediaHTML" exists in the "Media" metadata
    Then "MediaHTML" MUST be "String" data type
    And "MediaHTML" length SHOULD be less than or equal to the RESO Suggested Max Length of 8500

  @MediaKey @Media
  Scenario: MediaKey
    When "MediaKey" exists in the "Media" metadata
    Then "MediaKey" MUST be "String" data type
    And "MediaKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @MediaKeyNumeric @Media
  Scenario: MediaKeyNumeric
    When "MediaKeyNumeric" exists in the "Media" metadata
    Then "MediaKeyNumeric" MUST be "Integer" data type

  @MediaModificationTimestamp @Media
  Scenario: MediaModificationTimestamp
    When "MediaModificationTimestamp" exists in the "Media" metadata
    Then "MediaModificationTimestamp" MUST be "Timestamp" data type

  @MediaObjectID @Media
  Scenario: MediaObjectID
    When "MediaObjectID" exists in the "Media" metadata
    Then "MediaObjectID" MUST be "String" data type
    And "MediaObjectID" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @MediaStatus @Media
  Scenario: MediaStatus
    When "MediaStatus" exists in the "Media" metadata
    Then "MediaStatus" MUST be "Single Enumeration" data type

  @MediaType @Media
  Scenario: MediaType
    When "MediaType" exists in the "Media" metadata
    Then "MediaType" MUST be "Single Enumeration" data type

  @MediaURL @Media
  Scenario: MediaURL
    When "MediaURL" exists in the "Media" metadata
    Then "MediaURL" MUST be "String" data type
    And "MediaURL" length SHOULD be less than or equal to the RESO Suggested Max Length of 8000

  @ModificationTimestamp @Media
  Scenario: ModificationTimestamp
    When "ModificationTimestamp" exists in the "Media" metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type

  @Order @Media
  Scenario: Order
    When "Order" exists in the "Media" metadata
    Then "Order" MUST be "Integer" data type

  @OriginatingSystemID @Media
  Scenario: OriginatingSystemID
    When "OriginatingSystemID" exists in the "Media" metadata
    Then "OriginatingSystemID" MUST be "String" data type
    And "OriginatingSystemID" length SHOULD be less than or equal to the RESO Suggested Max Length of 25

  @OriginatingSystemMediaKey @Media
  Scenario: OriginatingSystemMediaKey
    When "OriginatingSystemMediaKey" exists in the "Media" metadata
    Then "OriginatingSystemMediaKey" MUST be "String" data type
    And "OriginatingSystemMediaKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @OriginatingSystemName @Media
  Scenario: OriginatingSystemName
    When "OriginatingSystemName" exists in the "Media" metadata
    Then "OriginatingSystemName" MUST be "String" data type
    And "OriginatingSystemName" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @Permission @Media
  Scenario: Permission
    When "Permission" exists in the "Media" metadata
    Then "Permission" MUST be "Multiple Enumeration" data type

  @PreferredPhotoYN @Media
  Scenario: PreferredPhotoYN
    When "PreferredPhotoYN" exists in the "Media" metadata
    Then "PreferredPhotoYN" MUST be "Boolean" data type

  @ResourceName @Media
  Scenario: ResourceName
    When "ResourceName" exists in the "Media" metadata
    Then "ResourceName" MUST be "Single Enumeration" data type

  @ResourceRecordID @Media
  Scenario: ResourceRecordID
    When "ResourceRecordID" exists in the "Media" metadata
    Then "ResourceRecordID" MUST be "String" data type
    And "ResourceRecordID" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ResourceRecordKey @Media
  Scenario: ResourceRecordKey
    When "ResourceRecordKey" exists in the "Media" metadata
    Then "ResourceRecordKey" MUST be "String" data type
    And "ResourceRecordKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ResourceRecordKeyNumeric @Media
  Scenario: ResourceRecordKeyNumeric
    When "ResourceRecordKeyNumeric" exists in the "Media" metadata
    Then "ResourceRecordKeyNumeric" MUST be "Integer" data type

  @ShortDescription @Media
  Scenario: ShortDescription
    When "ShortDescription" exists in the "Media" metadata
    Then "ShortDescription" MUST be "String" data type
    And "ShortDescription" length SHOULD be less than or equal to the RESO Suggested Max Length of 50

  @SourceSystemID @Media
  Scenario: SourceSystemID
    When "SourceSystemID" exists in the "Media" metadata
    Then "SourceSystemID" MUST be "String" data type
    And "SourceSystemID" length SHOULD be less than or equal to the RESO Suggested Max Length of 25

  @SourceSystemMediaKey @Media
  Scenario: SourceSystemMediaKey
    When "SourceSystemMediaKey" exists in the "Media" metadata
    Then "SourceSystemMediaKey" MUST be "String" data type
    And "SourceSystemMediaKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @SourceSystemName @Media
  Scenario: SourceSystemName
    When "SourceSystemName" exists in the "Media" metadata
    Then "SourceSystemName" MUST be "String" data type
    And "SourceSystemName" length SHOULD be less than or equal to the RESO Suggested Max Length of 255
