# This file was autogenerated on: 20200415150423335
Feature: Member

  @JobTitle
  Scenario: JobTitle
    Given "JobTitle" exists in the metadata
    Then "JobTitle" MUST be "String" data type
    And "JobTitle" length should be less than or equal to the RESO Suggested Max Length of 50

  @LastLoginTimestamp
  Scenario: LastLoginTimestamp
    Given "LastLoginTimestamp" exists in the metadata
    Then "LastLoginTimestamp" MUST be "Timestamp" data type
    And "LastLoginTimestamp" length should be less than or equal to the RESO Suggested Max Length of 27

  @MemberAOR
  Scenario: MemberAOR
    Given "MemberAOR" exists in the metadata
    And "MemberAOR" enum values exist in the metadata
    And "MemberAOR" enum types MUST have at least one member
    Then "MemberAOR" MUST be "String" data type
    And "MemberAOR" should only contain enum values found in the metadata
    And "MemberAOR" enumerations must match  MUST have annotations if they contain special characters
    And "MemberAOR" length should be less than or equal to the RESO Suggested Max Length of 50

  @MemberAORMlsId
  Scenario: MemberAORMlsId
    Given "MemberAORMlsId" exists in the metadata
    Then "MemberAORMlsId" MUST be "String" data type
    And "MemberAORMlsId" length should be less than or equal to the RESO Suggested Max Length of 25

  @MemberAORkey
  Scenario: MemberAORkey
    Given "MemberAORkey" exists in the metadata
    Then "MemberAORkey" MUST be "String" data type
    And "MemberAORkey" length should be less than or equal to the RESO Suggested Max Length of 255

  @MemberAORkeyNumeric
  Scenario: MemberAORkeyNumeric
    Given "MemberAORkeyNumeric" exists in the metadata
    Then "MemberAORkeyNumeric" MUST be "Integer" data type

  @MemberAddress1
  Scenario: MemberAddress1
    Given "MemberAddress1" exists in the metadata
    Then "MemberAddress1" MUST be "String" data type
    And "MemberAddress1" length should be less than or equal to the RESO Suggested Max Length of 50

  @MemberAddress2
  Scenario: MemberAddress2
    Given "MemberAddress2" exists in the metadata
    Then "MemberAddress2" MUST be "String" data type
    And "MemberAddress2" length should be less than or equal to the RESO Suggested Max Length of 50

  @MemberAssociationComments
  Scenario: MemberAssociationComments
    Given "MemberAssociationComments" exists in the metadata
    Then "MemberAssociationComments" MUST be "String" data type
    And "MemberAssociationComments" length should be less than or equal to the RESO Suggested Max Length of 500

  @MemberCarrierRoute
  Scenario: MemberCarrierRoute
    Given "MemberCarrierRoute" exists in the metadata
    Then "MemberCarrierRoute" MUST be "String" data type
    And "MemberCarrierRoute" length should be less than or equal to the RESO Suggested Max Length of 9

  @MemberCity
  Scenario: MemberCity
    Given "MemberCity" exists in the metadata
    Then "MemberCity" MUST be "String" data type
    And "MemberCity" length should be less than or equal to the RESO Suggested Max Length of 50

  @MemberCountry
  Scenario: MemberCountry
    Given "MemberCountry" exists in the metadata
    And "MemberCountry" enum values exist in the metadata
    And "MemberCountry" enum types MUST have at least one member
    Then "MemberCountry" MUST be "String" data type
    And "MemberCountry" should only contain enum values found in the metadata
    And "MemberCountry" enumerations must match  MUST have annotations if they contain special characters
    And "MemberCountry" length should be less than or equal to the RESO Suggested Max Length of 2

  @MemberCountyOrParish
  Scenario: MemberCountyOrParish
    Given "MemberCountyOrParish" exists in the metadata
    And "MemberCountyOrParish" enum values exist in the metadata
    And "MemberCountyOrParish" enum types MUST have at least one member
    Then "MemberCountyOrParish" MUST be "String" data type
    And "MemberCountyOrParish" should only contain enum values found in the metadata
    And "MemberCountyOrParish" enumerations must match  MUST have annotations if they contain special characters
    And "MemberCountyOrParish" length should be less than or equal to the RESO Suggested Max Length of 50

  @MemberDesignation
  Scenario: MemberDesignation
    Given "MemberDesignation" exists in the metadata
    And "MemberDesignation" enum values exist in the metadata
    And "MemberDesignation" enum types MUST have at least one member
    Then "MemberDesignation" MUST be "String Array" data type
    And RESO enumerations for "MemberDesignation" MUST have annotations if they contain special characters
    And "MemberDesignation" length should be less than or equal to the RESO Suggested Max Length of 50

  @MemberDirectPhone
  Scenario: MemberDirectPhone
    Given "MemberDirectPhone" exists in the metadata
    Then "MemberDirectPhone" MUST be "String" data type
    And "MemberDirectPhone" length should be less than or equal to the RESO Suggested Max Length of 16

  @MemberEmail
  Scenario: MemberEmail
    Given "MemberEmail" exists in the metadata
    Then "MemberEmail" MUST be "String" data type
    And "MemberEmail" length should be less than or equal to the RESO Suggested Max Length of 80

  @MemberFax
  Scenario: MemberFax
    Given "MemberFax" exists in the metadata
    Then "MemberFax" MUST be "String" data type
    And "MemberFax" length should be less than or equal to the RESO Suggested Max Length of 16

  @MemberFirstName
  Scenario: MemberFirstName
    Given "MemberFirstName" exists in the metadata
    Then "MemberFirstName" MUST be "String" data type
    And "MemberFirstName" length should be less than or equal to the RESO Suggested Max Length of 50

  @MemberFullName
  Scenario: MemberFullName
    Given "MemberFullName" exists in the metadata
    Then "MemberFullName" MUST be "String" data type
    And "MemberFullName" length should be less than or equal to the RESO Suggested Max Length of 150

  @MemberHomePhone
  Scenario: MemberHomePhone
    Given "MemberHomePhone" exists in the metadata
    Then "MemberHomePhone" MUST be "String" data type
    And "MemberHomePhone" length should be less than or equal to the RESO Suggested Max Length of 16

  @MemberIsAssistantTo
  Scenario: MemberIsAssistantTo
    Given "MemberIsAssistantTo" exists in the metadata
    Then "MemberIsAssistantTo" MUST be "String" data type
    And "MemberIsAssistantTo" length should be less than or equal to the RESO Suggested Max Length of 50

  @MemberKey
  Scenario: MemberKey
    Given "MemberKey" exists in the metadata
    Then "MemberKey" MUST be "String" data type
    And "MemberKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @MemberKeyNumeric
  Scenario: MemberKeyNumeric
    Given "MemberKeyNumeric" exists in the metadata
    Then "MemberKeyNumeric" MUST be "Integer" data type

  @MemberLanguages
  Scenario: MemberLanguages
    Given "MemberLanguages" exists in the metadata
    And "MemberLanguages" enum values exist in the metadata
    And "MemberLanguages" enum types MUST have at least one member
    Then "MemberLanguages" MUST be "String Array" data type
    And RESO enumerations for "MemberLanguages" MUST have annotations if they contain special characters
    And "MemberLanguages" length should be less than or equal to the RESO Suggested Max Length of 1024

  @MemberLastName
  Scenario: MemberLastName
    Given "MemberLastName" exists in the metadata
    Then "MemberLastName" MUST be "String" data type
    And "MemberLastName" length should be less than or equal to the RESO Suggested Max Length of 50

  @MemberLoginId
  Scenario: MemberLoginId
    Given "MemberLoginId" exists in the metadata
    Then "MemberLoginId" MUST be "String" data type
    And "MemberLoginId" length should be less than or equal to the RESO Suggested Max Length of 25

  @MemberMiddleName
  Scenario: MemberMiddleName
    Given "MemberMiddleName" exists in the metadata
    Then "MemberMiddleName" MUST be "String" data type
    And "MemberMiddleName" length should be less than or equal to the RESO Suggested Max Length of 50

  @MemberMlsAccessYN
  Scenario: MemberMlsAccessYN
    Given "MemberMlsAccessYN" exists in the metadata
    Then "MemberMlsAccessYN" MUST be "Boolean" data type

  @MemberMlsId
  Scenario: MemberMlsId
    Given "MemberMlsId" exists in the metadata
    Then "MemberMlsId" MUST be "String" data type
    And "MemberMlsId" length should be less than or equal to the RESO Suggested Max Length of 25

  @MemberMlsSecurityClass
  Scenario: MemberMlsSecurityClass
    Given "MemberMlsSecurityClass" exists in the metadata
    And "MemberMlsSecurityClass" enum values exist in the metadata
    And "MemberMlsSecurityClass" enum types MUST have at least one member
    Then "MemberMlsSecurityClass" MUST be "String" data type
    And "MemberMlsSecurityClass" should only contain enum values found in the metadata
    And "MemberMlsSecurityClass" enumerations must match  MUST have annotations if they contain special characters
    And "MemberMlsSecurityClass" length should be less than or equal to the RESO Suggested Max Length of 25

  @MemberMobilePhone
  Scenario: MemberMobilePhone
    Given "MemberMobilePhone" exists in the metadata
    Then "MemberMobilePhone" MUST be "String" data type
    And "MemberMobilePhone" length should be less than or equal to the RESO Suggested Max Length of 16

  @MemberNamePrefix
  Scenario: MemberNamePrefix
    Given "MemberNamePrefix" exists in the metadata
    Then "MemberNamePrefix" MUST be "String" data type
    And "MemberNamePrefix" length should be less than or equal to the RESO Suggested Max Length of 10

  @MemberNameSuffix
  Scenario: MemberNameSuffix
    Given "MemberNameSuffix" exists in the metadata
    Then "MemberNameSuffix" MUST be "String" data type
    And "MemberNameSuffix" length should be less than or equal to the RESO Suggested Max Length of 10

  @MemberNationalAssociationId
  Scenario: MemberNationalAssociationId
    Given "MemberNationalAssociationId" exists in the metadata
    Then "MemberNationalAssociationId" MUST be "String" data type
    And "MemberNationalAssociationId" length should be less than or equal to the RESO Suggested Max Length of 25

  @MemberNickname
  Scenario: MemberNickname
    Given "MemberNickname" exists in the metadata
    Then "MemberNickname" MUST be "String" data type
    And "MemberNickname" length should be less than or equal to the RESO Suggested Max Length of 50

  @MemberOfficePhone
  Scenario: MemberOfficePhone
    Given "MemberOfficePhone" exists in the metadata
    Then "MemberOfficePhone" MUST be "String" data type
    And "MemberOfficePhone" length should be less than or equal to the RESO Suggested Max Length of 16

  @MemberOfficePhoneExt
  Scenario: MemberOfficePhoneExt
    Given "MemberOfficePhoneExt" exists in the metadata
    Then "MemberOfficePhoneExt" MUST be "String" data type
    And "MemberOfficePhoneExt" length should be less than or equal to the RESO Suggested Max Length of 10

  @MemberOtherPhoneType
  Scenario: MemberOtherPhoneType
    Given "MemberOtherPhoneType" exists in the metadata
    And "MemberOtherPhoneType" enum values exist in the metadata
    And "MemberOtherPhoneType" enum types MUST have at least one member
    Then "MemberOtherPhoneType" MUST be "String" data type
    And "MemberOtherPhoneType" should only contain enum values found in the metadata
    And "MemberOtherPhoneType" enumerations must match  MUST have annotations if they contain special characters
    And "MemberOtherPhoneType" length should be less than or equal to the RESO Suggested Max Length of 25

  @MemberOtherPhone[Type]Ext
  Scenario: MemberOtherPhone[Type]Ext
    Given "MemberOtherPhone[Type]Ext" exists in the metadata
    Then "MemberOtherPhone[Type]Ext" MUST be "String" data type
    And "MemberOtherPhone[Type]Ext" length should be less than or equal to the RESO Suggested Max Length of 10

  @MemberOtherPhone[Type]Number
  Scenario: MemberOtherPhone[Type]Number
    Given "MemberOtherPhone[Type]Number" exists in the metadata
    Then "MemberOtherPhone[Type]Number" MUST be "String" data type
    And "MemberOtherPhone[Type]Number" length should be less than or equal to the RESO Suggested Max Length of 16

  @MemberPager
  Scenario: MemberPager
    Given "MemberPager" exists in the metadata
    Then "MemberPager" MUST be "String" data type
    And "MemberPager" length should be less than or equal to the RESO Suggested Max Length of 16

  @MemberPassword
  Scenario: MemberPassword
    Given "MemberPassword" exists in the metadata
    Then "MemberPassword" MUST be "String" data type
    And "MemberPassword" length should be less than or equal to the RESO Suggested Max Length of 25

  @MemberPhoneTTYTDD
  Scenario: MemberPhoneTTYTDD
    Given "MemberPhoneTTYTDD" exists in the metadata
    Then "MemberPhoneTTYTDD" MUST be "String" data type
    And "MemberPhoneTTYTDD" length should be less than or equal to the RESO Suggested Max Length of 16

  @MemberPostalCode
  Scenario: MemberPostalCode
    Given "MemberPostalCode" exists in the metadata
    Then "MemberPostalCode" MUST be "String" data type
    And "MemberPostalCode" length should be less than or equal to the RESO Suggested Max Length of 10

  @MemberPostalCodePlus4
  Scenario: MemberPostalCodePlus4
    Given "MemberPostalCodePlus4" exists in the metadata
    Then "MemberPostalCodePlus4" MUST be "String" data type
    And "MemberPostalCodePlus4" length should be less than or equal to the RESO Suggested Max Length of 4

  @MemberPreferredPhone
  Scenario: MemberPreferredPhone
    Given "MemberPreferredPhone" exists in the metadata
    Then "MemberPreferredPhone" MUST be "String" data type
    And "MemberPreferredPhone" length should be less than or equal to the RESO Suggested Max Length of 16

  @MemberPreferredPhoneExt
  Scenario: MemberPreferredPhoneExt
    Given "MemberPreferredPhoneExt" exists in the metadata
    Then "MemberPreferredPhoneExt" MUST be "String" data type
    And "MemberPreferredPhoneExt" length should be less than or equal to the RESO Suggested Max Length of 10

  @MemberStateLicense
  Scenario: MemberStateLicense
    Given "MemberStateLicense" exists in the metadata
    Then "MemberStateLicense" MUST be "String" data type
    And "MemberStateLicense" length should be less than or equal to the RESO Suggested Max Length of 50

  @MemberStateLicenseState
  Scenario: MemberStateLicenseState
    Given "MemberStateLicenseState" exists in the metadata
    And "MemberStateLicenseState" enum values exist in the metadata
    And "MemberStateLicenseState" enum types MUST have at least one member
    Then "MemberStateLicenseState" MUST be "String" data type
    And "MemberStateLicenseState" should only contain enum values found in the metadata
    And "MemberStateLicenseState" enumerations must match  MUST have annotations if they contain special characters
    And "MemberStateLicenseState" length should be less than or equal to the RESO Suggested Max Length of 2

  @MemberStateOrProvince
  Scenario: MemberStateOrProvince
    Given "MemberStateOrProvince" exists in the metadata
    And "MemberStateOrProvince" enum values exist in the metadata
    And "MemberStateOrProvince" enum types MUST have at least one member
    Then "MemberStateOrProvince" MUST be "String" data type
    And "MemberStateOrProvince" should only contain enum values found in the metadata
    And "MemberStateOrProvince" enumerations must match  MUST have annotations if they contain special characters
    And "MemberStateOrProvince" length should be less than or equal to the RESO Suggested Max Length of 2

  @MemberStatus
  Scenario: MemberStatus
    Given "MemberStatus" exists in the metadata
    And "MemberStatus" enum values exist in the metadata
    And "MemberStatus" enum types MUST have at least one member
    Then "MemberStatus" MUST be "String" data type
    And "MemberStatus" should only contain enum values found in the metadata
    And "MemberStatus" enumerations must match  MUST have annotations if they contain special characters
    And "MemberStatus" length should be less than or equal to the RESO Suggested Max Length of 25

  @MemberTollFreePhone
  Scenario: MemberTollFreePhone
    Given "MemberTollFreePhone" exists in the metadata
    Then "MemberTollFreePhone" MUST be "String" data type
    And "MemberTollFreePhone" length should be less than or equal to the RESO Suggested Max Length of 16

  @MemberType
  Scenario: MemberType
    Given "MemberType" exists in the metadata
    And "MemberType" enum values exist in the metadata
    And "MemberType" enum types MUST have at least one member
    Then "MemberType" MUST be "String" data type
    And "MemberType" should only contain enum values found in the metadata
    And "MemberType" enumerations must match  MUST have annotations if they contain special characters
    And "MemberType" length should be less than or equal to the RESO Suggested Max Length of 50

  @MemberVoiceMail
  Scenario: MemberVoiceMail
    Given "MemberVoiceMail" exists in the metadata
    Then "MemberVoiceMail" MUST be "String" data type
    And "MemberVoiceMail" length should be less than or equal to the RESO Suggested Max Length of 16

  @MemberVoiceMailExt
  Scenario: MemberVoiceMailExt
    Given "MemberVoiceMailExt" exists in the metadata
    Then "MemberVoiceMailExt" MUST be "String" data type
    And "MemberVoiceMailExt" length should be less than or equal to the RESO Suggested Max Length of 10

  @ModificationTimestamp
  Scenario: ModificationTimestamp
    Given "ModificationTimestamp" exists in the metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type
    And "ModificationTimestamp" length should be less than or equal to the RESO Suggested Max Length of 27

  @OfficeKey
  Scenario: OfficeKey
    Given "OfficeKey" exists in the metadata
    Then "OfficeKey" MUST be "String" data type
    And "OfficeKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @OfficeKeyNumeric
  Scenario: OfficeKeyNumeric
    Given "OfficeKeyNumeric" exists in the metadata
    Then "OfficeKeyNumeric" MUST be "Integer" data type

  @OfficeMlsId
  Scenario: OfficeMlsId
    Given "OfficeMlsId" exists in the metadata
    Then "OfficeMlsId" MUST be "String" data type
    And "OfficeMlsId" length should be less than or equal to the RESO Suggested Max Length of 25

  @OfficeName
  Scenario: OfficeName
    Given "OfficeName" exists in the metadata
    Then "OfficeName" MUST be "String" data type
    And "OfficeName" length should be less than or equal to the RESO Suggested Max Length of 255

  @OriginalEntryTimestamp
  Scenario: OriginalEntryTimestamp
    Given "OriginalEntryTimestamp" exists in the metadata
    Then "OriginalEntryTimestamp" MUST be "Timestamp" data type
    And "OriginalEntryTimestamp" length should be less than or equal to the RESO Suggested Max Length of 27

  @OriginatingSystemID
  Scenario: OriginatingSystemID
    Given "OriginatingSystemID" exists in the metadata
    Then "OriginatingSystemID" MUST be "String" data type
    And "OriginatingSystemID" length should be less than or equal to the RESO Suggested Max Length of 25

  @OriginatingSystemMemberKey
  Scenario: OriginatingSystemMemberKey
    Given "OriginatingSystemMemberKey" exists in the metadata
    Then "OriginatingSystemMemberKey" MUST be "String" data type
    And "OriginatingSystemMemberKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @OriginatingSystemName
  Scenario: OriginatingSystemName
    Given "OriginatingSystemName" exists in the metadata
    Then "OriginatingSystemName" MUST be "String" data type
    And "OriginatingSystemName" length should be less than or equal to the RESO Suggested Max Length of 255

  @SocialMediaType
  Scenario: SocialMediaType
    Given "SocialMediaType" exists in the metadata
    And "SocialMediaType" enum values exist in the metadata
    And "SocialMediaType" enum types MUST have at least one member
    Then "SocialMediaType" MUST be "String" data type
    And "SocialMediaType" should only contain enum values found in the metadata
    And "SocialMediaType" enumerations must match  MUST have annotations if they contain special characters
    And "SocialMediaType" length should be less than or equal to the RESO Suggested Max Length of 25

  @SocialMedia[Type]UrlOrId
  Scenario: SocialMedia[Type]UrlOrId
    Given "SocialMedia[Type]UrlOrId" exists in the metadata
    Then "SocialMedia[Type]UrlOrId" MUST be "String" data type
    And "SocialMedia[Type]UrlOrId" length should be less than or equal to the RESO Suggested Max Length of 8000

  @SourceSystemID
  Scenario: SourceSystemID
    Given "SourceSystemID" exists in the metadata
    Then "SourceSystemID" MUST be "String" data type
    And "SourceSystemID" length should be less than or equal to the RESO Suggested Max Length of 25

  @SourceSystemMemberKey
  Scenario: SourceSystemMemberKey
    Given "SourceSystemMemberKey" exists in the metadata
    Then "SourceSystemMemberKey" MUST be "String" data type
    And "SourceSystemMemberKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @SourceSystemName
  Scenario: SourceSystemName
    Given "SourceSystemName" exists in the metadata
    Then "SourceSystemName" MUST be "String" data type
    And "SourceSystemName" length should be less than or equal to the RESO Suggested Max Length of 255

  @SyndicateTo
  Scenario: SyndicateTo
    Given "SyndicateTo" exists in the metadata
    And "SyndicateTo" enum values exist in the metadata
    And "SyndicateTo" enum types MUST have at least one member
    Then "SyndicateTo" MUST be "String Array" data type
    And RESO enumerations for "SyndicateTo" MUST have annotations if they contain special characters
    And "SyndicateTo" length should be less than or equal to the RESO Suggested Max Length of 1024
