# This file was autogenerated on: 20201014011044856
Feature: OpenHouse

  Background:
    Given a RESOScript or Metadata file are provided
    When a RESOScript file is provided
    Then Client Settings and Parameters can be read from the RESOScript
    And a test container was successfully created from the given RESOScript file
    And the test container uses an Authorization Code or Client Credentials for authentication
    And valid metadata were retrieved from the server
    When a metadata file is provided
    Then a test container was successfully created from the given metadata file
    And valid metadata are loaded into the test container

  @OpenHouse
  Scenario: AppointmentRequiredYN
    When "AppointmentRequiredYN" exists in the "OpenHouse" metadata
    Then "AppointmentRequiredYN" MUST be "Boolean" data type

  @OpenHouse @IDX
  Scenario: ListingId
    When "ListingId" exists in the "OpenHouse" metadata
    Then "ListingId" MUST be "String" data type
    And the following synonyms for "ListingId" MUST NOT exist in the metadata
      | MLNumber |
      | MLSNumber |
      | ListingNumber |
    And "ListingId" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OpenHouse @IDX
  Scenario: ListingKey
    When "ListingKey" exists in the "OpenHouse" metadata
    Then "ListingKey" MUST be "String" data type
    And the following synonyms for "ListingKey" MUST NOT exist in the metadata
      | SystemUniqueID |
      | ImmediateSourceID |
    And "ListingKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OpenHouse @IDX
  Scenario: ListingKeyNumeric
    When "ListingKeyNumeric" exists in the "OpenHouse" metadata
    Then "ListingKeyNumeric" MUST be "Integer" data type
    And the following synonyms for "ListingKeyNumeric" MUST NOT exist in the metadata
      | SystemUniqueID |
      | ImmediateSourceID |

  @OpenHouse @IDX
  Scenario: ModificationTimestamp
    When "ModificationTimestamp" exists in the "OpenHouse" metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type
    And the following synonyms for "ModificationTimestamp" MUST NOT exist in the metadata
      | ModificationDateTime |
      | DateTimeModified |
      | ModDate |
      | DateMod |
      | UpdateDate |
      | UpdateTimestamp |

  @OpenHouse
  Scenario: OpenHouseAttendedBy
    When "OpenHouseAttendedBy" exists in the "OpenHouse" metadata
    Then "OpenHouseAttendedBy" MUST be "Single Enumeration" data type
    And "OpenHouseAttendedBy" MAY contain any of the following standard lookups
      | lookupValue | lookupDisplayName |
      | Agent | Agent |
      | Seller | Seller |
      | Unattended | Unattended |

  @OpenHouse @IDX
  Scenario: OpenHouseDate
    When "OpenHouseDate" exists in the "OpenHouse" metadata
    Then "OpenHouseDate" MUST be "Date" data type

  @OpenHouse @IDX
  Scenario: OpenHouseEndTime
    When "OpenHouseEndTime" exists in the "OpenHouse" metadata
    Then "OpenHouseEndTime" MUST be "Timestamp" data type

  @OpenHouse
  Scenario: OpenHouseId
    When "OpenHouseId" exists in the "OpenHouse" metadata
    Then "OpenHouseId" MUST be "String" data type
    And "OpenHouseId" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OpenHouse @IDX
  Scenario: OpenHouseKey
    When "OpenHouseKey" exists in the "OpenHouse" metadata
    Then "OpenHouseKey" MUST be "String" data type
    And "OpenHouseKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OpenHouse @IDX
  Scenario: OpenHouseKeyNumeric
    When "OpenHouseKeyNumeric" exists in the "OpenHouse" metadata
    Then "OpenHouseKeyNumeric" MUST be "Integer" data type

  @OpenHouse @IDX
  Scenario: OpenHouseRemarks
    When "OpenHouseRemarks" exists in the "OpenHouse" metadata
    Then "OpenHouseRemarks" MUST be "String" data type
    And "OpenHouseRemarks" length SHOULD be equal to the RESO Suggested Max Length of 500

  @OpenHouse @IDX
  Scenario: OpenHouseStartTime
    When "OpenHouseStartTime" exists in the "OpenHouse" metadata
    Then "OpenHouseStartTime" MUST be "Timestamp" data type

  @OpenHouse @IDX
  Scenario: OpenHouseStatus
    When "OpenHouseStatus" exists in the "OpenHouse" metadata
    Then "OpenHouseStatus" MUST be "Single Enumeration" data type
    And "OpenHouseStatus" MAY contain any of the following standard lookups
      | lookupValue | lookupDisplayName |
      | Active | Active |
      | Canceled | Canceled |
      | Ended | Ended |

  @OpenHouse @IDX
  Scenario: OpenHouseType
    When "OpenHouseType" exists in the "OpenHouse" metadata
    Then "OpenHouseType" MUST be "Single Enumeration" data type
    And "OpenHouseType" MAY contain any of the following standard lookups
      | lookupValue | lookupDisplayName |
      | Broker | Broker |
      | Office | Office |
      | Public | Public |

  @OpenHouse @IDX
  Scenario: OriginalEntryTimestamp
    When "OriginalEntryTimestamp" exists in the "OpenHouse" metadata
    Then "OriginalEntryTimestamp" MUST be "Timestamp" data type
    And the following synonyms for "OriginalEntryTimestamp" MUST NOT exist in the metadata
      | EntryDate |
      | InputDate |
      | DateTimeCreated |
      | CreatedDate. |

  @OpenHouse @IDX
  Scenario: OriginatingSystemID
    When "OriginatingSystemID" exists in the "OpenHouse" metadata
    Then "OriginatingSystemID" MUST be "String" data type
    And "OriginatingSystemID" length SHOULD be equal to the RESO Suggested Max Length of 25

  @OpenHouse @IDX
  Scenario: OriginatingSystemKey
    When "OriginatingSystemKey" exists in the "OpenHouse" metadata
    Then "OriginatingSystemKey" MUST be "String" data type
    And the following synonyms for "OriginatingSystemKey" MUST NOT exist in the metadata
      | ProviderKey |
    And "OriginatingSystemKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OpenHouse
  Scenario: OriginatingSystemName
    When "OriginatingSystemName" exists in the "OpenHouse" metadata
    Then "OriginatingSystemName" MUST be "String" data type
    And the following synonyms for "OriginatingSystemName" MUST NOT exist in the metadata
      | ProviderName |
      | MLSID |
    And "OriginatingSystemName" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OpenHouse @IDX
  Scenario: Refreshments
    When "Refreshments" exists in the "OpenHouse" metadata
    Then "Refreshments" MUST be "String" data type
    And "Refreshments" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OpenHouse
  Scenario: ShowingAgentFirstName
    When "ShowingAgentFirstName" exists in the "OpenHouse" metadata
    Then "ShowingAgentFirstName" MUST be "String" data type
    And the following synonyms for "ShowingAgentFirstName" MUST NOT exist in the metadata
      | ShowingMemberFirstName |
    And "ShowingAgentFirstName" length SHOULD be equal to the RESO Suggested Max Length of 50

  @OpenHouse @IDX
  Scenario: ShowingAgentKey
    When "ShowingAgentKey" exists in the "OpenHouse" metadata
    Then "ShowingAgentKey" MUST be "String" data type
    And the following synonyms for "ShowingAgentKey" MUST NOT exist in the metadata
      | ShowingMemberKey |
    And "ShowingAgentKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OpenHouse @IDX
  Scenario: ShowingAgentKeyNumeric
    When "ShowingAgentKeyNumeric" exists in the "OpenHouse" metadata
    Then "ShowingAgentKeyNumeric" MUST be "Integer" data type
    And the following synonyms for "ShowingAgentKeyNumeric" MUST NOT exist in the metadata
      | ShowingMemberKeyNumeric |

  @OpenHouse
  Scenario: ShowingAgentLastName
    When "ShowingAgentLastName" exists in the "OpenHouse" metadata
    Then "ShowingAgentLastName" MUST be "String" data type
    And the following synonyms for "ShowingAgentLastName" MUST NOT exist in the metadata
      | ShowingMemberLastName |
    And "ShowingAgentLastName" length SHOULD be equal to the RESO Suggested Max Length of 50

  @OpenHouse
  Scenario: ShowingAgentMlsID
    When "ShowingAgentMlsID" exists in the "OpenHouse" metadata
    Then "ShowingAgentMlsID" MUST be "String" data type
    And the following synonyms for "ShowingAgentMlsID" MUST NOT exist in the metadata
      | ShowingMemberMlslD |
    And "ShowingAgentMlsID" length SHOULD be equal to the RESO Suggested Max Length of 25

  @OpenHouse @IDX
  Scenario: SourceSystemID
    When "SourceSystemID" exists in the "OpenHouse" metadata
    Then "SourceSystemID" MUST be "String" data type
    And the following synonyms for "SourceSystemID" MUST NOT exist in the metadata
      | MLSID |
    And "SourceSystemID" length SHOULD be equal to the RESO Suggested Max Length of 25

  @OpenHouse @IDX
  Scenario: SourceSystemKey
    When "SourceSystemKey" exists in the "OpenHouse" metadata
    Then "SourceSystemKey" MUST be "String" data type
    And the following synonyms for "SourceSystemKey" MUST NOT exist in the metadata
      | ProviderKey |
    And "SourceSystemKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OpenHouse
  Scenario: SourceSystemName
    When "SourceSystemName" exists in the "OpenHouse" metadata
    Then "SourceSystemName" MUST be "String" data type
    And the following synonyms for "SourceSystemName" MUST NOT exist in the metadata
      | ProviderName |
      | MLSID |
    And "SourceSystemName" length SHOULD be equal to the RESO Suggested Max Length of 255
