# This file was autogenerated on: 20200929220925944
Feature: PropertyRooms

  Background:
    Given a RESOScript or Metadata file are provided
    When a RESOScript file is provided
    Then Client Settings and Parameters can be read from the RESOScript
    And a test container was successfully created from the given RESOScript file
    And the test container uses an Authorization Code or Client Credentials for authentication
    And valid metadata were retrieved from the server
    When a metadata file is provided
    Then a test container was successfully created from the given metadata file
    And valid metadata are loaded into the test container

  @ListingId @PropertyRooms
  Scenario: ListingId
    When "ListingId" exists in the "PropertyRooms" metadata
    Then "ListingId" MUST be "String" data type
    And "ListingId" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ListingKey @PropertyRooms
  Scenario: ListingKey
    When "ListingKey" exists in the "PropertyRooms" metadata
    Then "ListingKey" MUST be "String" data type
    And "ListingKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ListingKeyNumeric @PropertyRooms
  Scenario: ListingKeyNumeric
    When "ListingKeyNumeric" exists in the "PropertyRooms" metadata
    Then "ListingKeyNumeric" MUST be "Integer" data type

  @ModificationTimestamp @PropertyRooms
  Scenario: ModificationTimestamp
    When "ModificationTimestamp" exists in the "PropertyRooms" metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type

  @RoomArea @PropertyRooms
  Scenario: RoomArea
    When "RoomArea" exists in the "PropertyRooms" metadata
    Then "RoomArea" MUST be "Decimal" data type
    And "RoomArea" precision SHOULD be less than or equal to the RESO Suggested Max Length of 14
    And "RoomArea" scale SHOULD be less than or equal to the RESO Suggested Max Scale of 2

  @RoomAreaSource @PropertyRooms
  Scenario: RoomAreaSource
    When "RoomAreaSource" exists in the "PropertyRooms" metadata
    Then "RoomAreaSource" MUST be "Single Enumeration" data type

  @RoomAreaUnits @PropertyRooms
  Scenario: RoomAreaUnits
    When "RoomAreaUnits" exists in the "PropertyRooms" metadata
    Then "RoomAreaUnits" MUST be "Single Enumeration" data type

  @RoomDescription @PropertyRooms
  Scenario: RoomDescription
    When "RoomDescription" exists in the "PropertyRooms" metadata
    Then "RoomDescription" MUST be "String" data type
    And "RoomDescription" length SHOULD be less than or equal to the RESO Suggested Max Length of 1024

  @RoomDimensions @PropertyRooms
  Scenario: RoomDimensions
    When "RoomDimensions" exists in the "PropertyRooms" metadata
    Then "RoomDimensions" MUST be "String" data type
    And "RoomDimensions" length SHOULD be less than or equal to the RESO Suggested Max Length of 50

  @RoomFeatures @PropertyRooms
  Scenario: RoomFeatures
    When "RoomFeatures" exists in the "PropertyRooms" metadata
    Then "RoomFeatures" MUST be "Multiple Enumeration" data type

  @RoomKey @PropertyRooms
  Scenario: RoomKey
    When "RoomKey" exists in the "PropertyRooms" metadata
    Then "RoomKey" MUST be "String" data type
    And "RoomKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @RoomKeyNumeric @PropertyRooms
  Scenario: RoomKeyNumeric
    When "RoomKeyNumeric" exists in the "PropertyRooms" metadata
    Then "RoomKeyNumeric" MUST be "Integer" data type

  @RoomLength @PropertyRooms
  Scenario: RoomLength
    When "RoomLength" exists in the "PropertyRooms" metadata
    Then "RoomLength" MUST be "Decimal" data type
    And "RoomLength" precision SHOULD be less than or equal to the RESO Suggested Max Length of 14
    And "RoomLength" scale SHOULD be less than or equal to the RESO Suggested Max Scale of 2

  @RoomLengthWidthUnits @PropertyRooms
  Scenario: RoomLengthWidthUnits
    When "RoomLengthWidthUnits" exists in the "PropertyRooms" metadata
    Then "RoomLengthWidthUnits" MUST be "Single Enumeration" data type

  @RoomType @PropertyRooms
  Scenario: RoomType
    When "RoomType" exists in the "PropertyRooms" metadata
    Then "RoomType" MUST be "Single Enumeration" data type

  @RoomWidth @PropertyRooms
  Scenario: RoomWidth
    When "RoomWidth" exists in the "PropertyRooms" metadata
    Then "RoomWidth" MUST be "Decimal" data type
    And "RoomWidth" precision SHOULD be less than or equal to the RESO Suggested Max Length of 14
    And "RoomWidth" scale SHOULD be less than or equal to the RESO Suggested Max Scale of 2
