# This file was autogenerated on: 20200415150423335
Feature: PropertyUnitTypes

  @ListingId
  Scenario: ListingId
    Given "ListingId" exists in the metadata
    Then "ListingId" MUST be "String" data type
    And "ListingId" length should be less than or equal to the RESO Suggested Max Length of 255

  @ListingKey
  Scenario: ListingKey
    Given "ListingKey" exists in the metadata
    Then "ListingKey" MUST be "String" data type
    And "ListingKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @ListingKeyNumeric
  Scenario: ListingKeyNumeric
    Given "ListingKeyNumeric" exists in the metadata
    Then "ListingKeyNumeric" MUST be "Integer" data type

  @ModificationTimestamp
  Scenario: ModificationTimestamp
    Given "ModificationTimestamp" exists in the metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type
    And "ModificationTimestamp" length should be less than or equal to the RESO Suggested Max Length of 27

  @UnitTypeActualRent
  Scenario: UnitTypeActualRent
    Given "UnitTypeActualRent" exists in the metadata
    Then "UnitTypeActualRent" MUST be "Decimal" data type
    And "UnitTypeActualRent" precision should be less than or equal to the RESO Suggested Max Length of 14
    And "UnitTypeActualRent" scale should be less than or equal to the RESO Suggested Max Scale of 2

  @UnitTypeBathsTotal
  Scenario: UnitTypeBathsTotal
    Given "UnitTypeBathsTotal" exists in the metadata
    Then "UnitTypeBathsTotal" MUST be "Integer" data type

  @UnitTypeBedsTotal
  Scenario: UnitTypeBedsTotal
    Given "UnitTypeBedsTotal" exists in the metadata
    Then "UnitTypeBedsTotal" MUST be "Integer" data type

  @UnitTypeDescription
  Scenario: UnitTypeDescription
    Given "UnitTypeDescription" exists in the metadata
    Then "UnitTypeDescription" MUST be "String" data type
    And "UnitTypeDescription" length should be less than or equal to the RESO Suggested Max Length of 1024

  @UnitTypeFurnished
  Scenario: UnitTypeFurnished
    Given "UnitTypeFurnished" exists in the metadata
    And "UnitTypeFurnished" enum values exist in the metadata
    And "UnitTypeFurnished" enum types MUST have at least one member
    Then "UnitTypeFurnished" MUST be "String" data type
    And "UnitTypeFurnished" should only contain enum values found in the metadata
    And "UnitTypeFurnished" enumerations must match  MUST have annotations if they contain special characters
    And "UnitTypeFurnished" length should be less than or equal to the RESO Suggested Max Length of 20

  @UnitTypeGarageAttachedYN
  Scenario: UnitTypeGarageAttachedYN
    Given "UnitTypeGarageAttachedYN" exists in the metadata
    Then "UnitTypeGarageAttachedYN" MUST be "Boolean" data type

  @UnitTypeGarageSpaces
  Scenario: UnitTypeGarageSpaces
    Given "UnitTypeGarageSpaces" exists in the metadata
    Then "UnitTypeGarageSpaces" MUST be "Decimal" data type
    And "UnitTypeGarageSpaces" precision should be less than or equal to the RESO Suggested Max Length of 14
    And "UnitTypeGarageSpaces" scale should be less than or equal to the RESO Suggested Max Scale of 2

  @UnitTypeKey
  Scenario: UnitTypeKey
    Given "UnitTypeKey" exists in the metadata
    Then "UnitTypeKey" MUST be "String" data type
    And "UnitTypeKey" length should be less than or equal to the RESO Suggested Max Length of 255

  @UnitTypeKeyNumeric
  Scenario: UnitTypeKeyNumeric
    Given "UnitTypeKeyNumeric" exists in the metadata
    Then "UnitTypeKeyNumeric" MUST be "Integer" data type

  @UnitTypeProForma
  Scenario: UnitTypeProForma
    Given "UnitTypeProForma" exists in the metadata
    Then "UnitTypeProForma" MUST be "Integer" data type

  @UnitTypeTotalRent
  Scenario: UnitTypeTotalRent
    Given "UnitTypeTotalRent" exists in the metadata
    Then "UnitTypeTotalRent" MUST be "Decimal" data type
    And "UnitTypeTotalRent" precision should be less than or equal to the RESO Suggested Max Length of 14
    And "UnitTypeTotalRent" scale should be less than or equal to the RESO Suggested Max Scale of 2

  @UnitTypeType
  Scenario: UnitTypeType
    Given "UnitTypeType" exists in the metadata
    And "UnitTypeType" enum values exist in the metadata
    And "UnitTypeType" enum types MUST have at least one member
    Then "UnitTypeType" MUST be "String" data type
    And "UnitTypeType" should only contain enum values found in the metadata
    And "UnitTypeType" enumerations must match  MUST have annotations if they contain special characters
    And "UnitTypeType" length should be less than or equal to the RESO Suggested Max Length of 1024

  @UnitTypeUnitsTotal
  Scenario: UnitTypeUnitsTotal
    Given "UnitTypeUnitsTotal" exists in the metadata
    Then "UnitTypeUnitsTotal" MUST be "Integer" data type
