# This file was autogenerated on: 20200510010510583
Feature: Prospecting

  Background:
    Given a RESOScript file was provided
    And Client Settings and Parameters were read from the file
    And a test container was successfully created from the given RESOScript
    And the test container uses an Authorization Code or Client Credentials for authentication
    And metadata were retrieved from the server
    And metadata are valid

  @ActiveYN @Prospecting
Scenario: ActiveYN
    Given "ActiveYN" exists in the metadata
    And "ActiveYN" is not a synonym for another field
    Then "ActiveYN" MUST be "Boolean" data type

  @BccEmailList @Prospecting
  Scenario: BccEmailList
    Given "BccEmailList" exists in the metadata
    Then "BccEmailList" MUST be "String" data type
    And "BccEmailList" length SHOULD be less than or equal to the RESO Suggested Max Length of 1024

  @BccMeYN @Prospecting
Scenario: BccMeYN
    Given "BccMeYN" exists in the metadata
    And "BccMeYN" is not a synonym for another field
    Then "BccMeYN" MUST be "Boolean" data type

  @CcEmailList @Prospecting
  Scenario: CcEmailList
    Given "CcEmailList" exists in the metadata
    Then "CcEmailList" MUST be "String" data type
    And "CcEmailList" length SHOULD be less than or equal to the RESO Suggested Max Length of 1024

  @ClientActivatedYN @Prospecting
Scenario: ClientActivatedYN
    Given "ClientActivatedYN" exists in the metadata
    And "ClientActivatedYN" is not a synonym for another field
    Then "ClientActivatedYN" MUST be "Boolean" data type

  @ConciergeNotificationsYN @Prospecting
Scenario: ConciergeNotificationsYN
    Given "ConciergeNotificationsYN" exists in the metadata
    And "ConciergeNotificationsYN" is not a synonym for another field
    Then "ConciergeNotificationsYN" MUST be "Boolean" data type

  @ConciergeYN @Prospecting
Scenario: ConciergeYN
    Given "ConciergeYN" exists in the metadata
    And "ConciergeYN" is not a synonym for another field
    Then "ConciergeYN" MUST be "Boolean" data type

  @ContactKey @Prospecting
  Scenario: ContactKey
    Given "ContactKey" exists in the metadata
    Then "ContactKey" MUST be "String" data type
    And "ContactKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ContactKeyNumeric @Prospecting
  Scenario: ContactKeyNumeric
    Given "ContactKeyNumeric" exists in the metadata
    Then "ContactKeyNumeric" MUST be "Integer" data type

  @DailySchedule @Prospecting
  Scenario: DailySchedule
    Given "DailySchedule" exists in the metadata
    And "DailySchedule" enum values exist in the metadata
    And "DailySchedule" enum types MUST have at least one member
    Then "DailySchedule" MUST be "String Array" data type
    And "DailySchedule" SHOULD have no more than the RESO Suggested Max Length of 1024 item(s)

  @DisplayTemplateID @Prospecting
  Scenario: DisplayTemplateID
    Given "DisplayTemplateID" exists in the metadata
    Then "DisplayTemplateID" MUST be "String" data type
    And "DisplayTemplateID" length SHOULD be less than or equal to the RESO Suggested Max Length of 25

  @Language @Prospecting
  Scenario: Language
    Given "Language" exists in the metadata
    And "Language" enum values exist in the metadata
    And "Language" enum types MUST have exactly one member
    Then "Language" MUST be "String" data type
    And "Language" MUST only contain enum values found in the metadata
    And "Language" length SHOULD be less than or equal to the RESO Suggested Max Length of 25

  @LastNewChangedTimestamp @Prospecting
  Scenario: LastNewChangedTimestamp
    Given "LastNewChangedTimestamp" exists in the metadata
    Then "LastNewChangedTimestamp" MUST be "Timestamp" data type
    And "LastNewChangedTimestamp" length SHOULD be less than or equal to the RESO Suggested Max Length of 27

  @LastViewedTimestamp @Prospecting
  Scenario: LastViewedTimestamp
    Given "LastViewedTimestamp" exists in the metadata
    Then "LastViewedTimestamp" MUST be "Timestamp" data type
    And "LastViewedTimestamp" length SHOULD be less than or equal to the RESO Suggested Max Length of 27

  @MessageNew @Prospecting
  Scenario: MessageNew
    Given "MessageNew" exists in the metadata
    Then "MessageNew" MUST be "String" data type
    And "MessageNew" length SHOULD be less than or equal to the RESO Suggested Max Length of 4000

  @MessageRevise @Prospecting
  Scenario: MessageRevise
    Given "MessageRevise" exists in the metadata
    Then "MessageRevise" MUST be "String" data type
    And "MessageRevise" length SHOULD be less than or equal to the RESO Suggested Max Length of 4000

  @MessageUpdate @Prospecting
  Scenario: MessageUpdate
    Given "MessageUpdate" exists in the metadata
    Then "MessageUpdate" MUST be "String" data type
    And "MessageUpdate" length SHOULD be less than or equal to the RESO Suggested Max Length of 4000

  @ModificationTimestamp @Prospecting
  Scenario: ModificationTimestamp
    Given "ModificationTimestamp" exists in the metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type
    And "ModificationTimestamp" length SHOULD be less than or equal to the RESO Suggested Max Length of 27

  @NextSendTimestamp @Prospecting
  Scenario: NextSendTimestamp
    Given "NextSendTimestamp" exists in the metadata
    Then "NextSendTimestamp" MUST be "Timestamp" data type
    And "NextSendTimestamp" length SHOULD be less than or equal to the RESO Suggested Max Length of 27

  @OwnerMemberID @Prospecting
  Scenario: OwnerMemberID
    Given "OwnerMemberID" exists in the metadata
    Then "OwnerMemberID" MUST be "String" data type
    And "OwnerMemberID" length SHOULD be less than or equal to the RESO Suggested Max Length of 25

  @OwnerMemberKey @Prospecting
  Scenario: OwnerMemberKey
    Given "OwnerMemberKey" exists in the metadata
    Then "OwnerMemberKey" MUST be "String" data type
    And "OwnerMemberKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @OwnerMemberKeyNumeric @Prospecting
  Scenario: OwnerMemberKeyNumeric
    Given "OwnerMemberKeyNumeric" exists in the metadata
    Then "OwnerMemberKeyNumeric" MUST be "Integer" data type

  @ProspectingKey @Prospecting
  Scenario: ProspectingKey
    Given "ProspectingKey" exists in the metadata
    Then "ProspectingKey" MUST be "String" data type
    And "ProspectingKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ProspectingKeyNumeric @Prospecting
  Scenario: ProspectingKeyNumeric
    Given "ProspectingKeyNumeric" exists in the metadata
    Then "ProspectingKeyNumeric" MUST be "Integer" data type

  @ReasonActiveOrDisabled @Prospecting
  Scenario: ReasonActiveOrDisabled
    Given "ReasonActiveOrDisabled" exists in the metadata
    And "ReasonActiveOrDisabled" enum values exist in the metadata
    And "ReasonActiveOrDisabled" enum types MUST have exactly one member
    Then "ReasonActiveOrDisabled" MUST be "String" data type
    And "ReasonActiveOrDisabled" MUST only contain enum values found in the metadata
    And "ReasonActiveOrDisabled" length SHOULD be less than or equal to the RESO Suggested Max Length of 50

  @SavedSearchKey @Prospecting
  Scenario: SavedSearchKey
    Given "SavedSearchKey" exists in the metadata
    Then "SavedSearchKey" MUST be "String" data type
    And "SavedSearchKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @SavedSearchKeyNumeric @Prospecting
  Scenario: SavedSearchKeyNumeric
    Given "SavedSearchKeyNumeric" exists in the metadata
    Then "SavedSearchKeyNumeric" MUST be "Integer" data type

  @ScheduleType @Prospecting
  Scenario: ScheduleType
    Given "ScheduleType" exists in the metadata
    And "ScheduleType" enum values exist in the metadata
    And "ScheduleType" enum types MUST have exactly one member
    Then "ScheduleType" MUST be "String" data type
    And "ScheduleType" MUST only contain enum values found in the metadata
    And "ScheduleType" length SHOULD be less than or equal to the RESO Suggested Max Length of 25

  @Subject @Prospecting
  Scenario: Subject
    Given "Subject" exists in the metadata
    Then "Subject" MUST be "String" data type
    And "Subject" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ToEmailList @Prospecting
  Scenario: ToEmailList
    Given "ToEmailList" exists in the metadata
    Then "ToEmailList" MUST be "String" data type
    And "ToEmailList" length SHOULD be less than or equal to the RESO Suggested Max Length of 1024
