# This file was autogenerated on: 20200623200643815
Feature: SocialMedia

  Background:
    Given a RESOScript file was provided
    And Client Settings and Parameters were read from the file
    And a test container was successfully created from the given RESOScript
    And the test container uses an Authorization Code or Client Credentials for authentication
    And valid metadata were retrieved from the server

  @ClassName @SocialMedia
  Scenario: ClassName
    When "ClassName" exists in the "SocialMedia" metadata
    Then "ClassName" MUST be "Single Enumeration" data type

  @ModificationTimestamp @SocialMedia
  Scenario: ModificationTimestamp
    When "ModificationTimestamp" exists in the "SocialMedia" metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type

  @ResourceName @SocialMedia
  Scenario: ResourceName
    When "ResourceName" exists in the "SocialMedia" metadata
    Then "ResourceName" MUST be "Single Enumeration" data type

  @ResourceRecordID @SocialMedia
  Scenario: ResourceRecordID
    When "ResourceRecordID" exists in the "SocialMedia" metadata
    Then "ResourceRecordID" MUST be "String" data type
    And "ResourceRecordID" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ResourceRecordKey @SocialMedia
  Scenario: ResourceRecordKey
    When "ResourceRecordKey" exists in the "SocialMedia" metadata
    Then "ResourceRecordKey" MUST be "String" data type
    And "ResourceRecordKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @ResourceRecordKeyNumeric @SocialMedia
  Scenario: ResourceRecordKeyNumeric
    When "ResourceRecordKeyNumeric" exists in the "SocialMedia" metadata
    Then "ResourceRecordKeyNumeric" MUST be "Integer" data type

  @SocialMediaKey @SocialMedia
  Scenario: SocialMediaKey
    When "SocialMediaKey" exists in the "SocialMedia" metadata
    Then "SocialMediaKey" MUST be "String" data type
    And "SocialMediaKey" length SHOULD be less than or equal to the RESO Suggested Max Length of 255

  @SocialMediaKeyNumeric @SocialMedia
  Scenario: SocialMediaKeyNumeric
    When "SocialMediaKeyNumeric" exists in the "SocialMedia" metadata
    Then "SocialMediaKeyNumeric" MUST be "Integer" data type

  @SocialMediaType @SocialMedia
  Scenario: SocialMediaType
    When "SocialMediaType" exists in the "SocialMedia" metadata
    Then "SocialMediaType" MUST be "Single Enumeration" data type

  @SocialMediaUrlOrId @SocialMedia
  Scenario: SocialMediaUrlOrId
    When "SocialMediaUrlOrId" exists in the "SocialMedia" metadata
    Then "SocialMediaUrlOrId" MUST be "String" data type
    And "SocialMediaUrlOrId" length SHOULD be less than or equal to the RESO Suggested Max Length of 8000
