# This file was autogenerated on: 20201014221013332
Feature: Teams

  Background:
    Given a RESOScript or Metadata file are provided
    When a RESOScript file is provided
    Then Client Settings and Parameters can be read from the RESOScript
    And a test container was successfully created from the given RESOScript file
    And the test container uses an Authorization Code or Client Credentials for authentication
    And valid metadata were retrieved from the server
    When a metadata file is provided
    Then a test container was successfully created from the given metadata file
    And valid metadata are loaded into the test container

  @Teams
  Scenario: ModificationTimestamp
    When "ModificationTimestamp" exists in the "Teams" metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type

  @Teams
  Scenario: OriginalEntryTimestamp
    When "OriginalEntryTimestamp" exists in the "Teams" metadata
    Then "OriginalEntryTimestamp" MUST be "Timestamp" data type

  @Teams
  Scenario: OriginatingSystemID
    When "OriginatingSystemID" exists in the "Teams" metadata
    Then "OriginatingSystemID" MUST be "String" data type
    And "OriginatingSystemID" length SHOULD be equal to the RESO Suggested Max Length of 25

  @Teams
  Scenario: OriginatingSystemKey
    When "OriginatingSystemKey" exists in the "Teams" metadata
    Then "OriginatingSystemKey" MUST be "String" data type
    And "OriginatingSystemKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @Teams
  Scenario: OriginatingSystemName
    When "OriginatingSystemName" exists in the "Teams" metadata
    Then "OriginatingSystemName" MUST be "String" data type
    And the following synonyms for "OriginatingSystemName" MUST NOT exist in the metadata
      | ProviderName |
      | MLSID |
    And "OriginatingSystemName" length SHOULD be equal to the RESO Suggested Max Length of 255

  @Teams
  Scenario: SocialMediaType
    When "SocialMediaType" exists in the "Teams" metadata
    Then "SocialMediaType" MUST be "Single Enumeration" data type
    And "SocialMediaType" MAY contain any of the following standard lookups
      | lookupValue | lookupDisplayName |
      | Blog | Blog |
      | Digg | Digg |
      | Facebook | Facebook |
      | FacebookMessenger | Facebook Messenger |
      | Googleplus | GooglePlus |
      | iMessage | iMessage |
      | Instagram | Instagram |
      | Linkedin | LinkedIn |
      | Pinterest | Pinterest |
      | Reddit | Reddit |
      | Slack | Slack |
      | Snapchat | Snapchat |
      | Stumbleupon | StumbleUpon |
      | Tumblr | Tumblr |
      | Twitter | Twitter |
      | Website | Website |
      | Youtube | YouTube |

  @Teams
  Scenario: SourceSystemID
    When "SourceSystemID" exists in the "Teams" metadata
    Then "SourceSystemID" MUST be "String" data type
    And the following synonyms for "SourceSystemID" MUST NOT exist in the metadata
      | MLSID |
    And "SourceSystemID" length SHOULD be equal to the RESO Suggested Max Length of 25

  @Teams
  Scenario: SourceSystemKey
    When "SourceSystemKey" exists in the "Teams" metadata
    Then "SourceSystemKey" MUST be "String" data type
    And the following synonyms for "SourceSystemKey" MUST NOT exist in the metadata
      | ProviderKey |
    And "SourceSystemKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @Teams
  Scenario: SourceSystemName
    When "SourceSystemName" exists in the "Teams" metadata
    Then "SourceSystemName" MUST be "String" data type
    And the following synonyms for "SourceSystemName" MUST NOT exist in the metadata
      | ProviderName |
      | MLSID |
    And "SourceSystemName" length SHOULD be equal to the RESO Suggested Max Length of 255

  @Teams
  Scenario: TeamAddress1
    When "TeamAddress1" exists in the "Teams" metadata
    Then "TeamAddress1" MUST be "String" data type
    And "TeamAddress1" length SHOULD be equal to the RESO Suggested Max Length of 50

  @Teams
  Scenario: TeamAddress2
    When "TeamAddress2" exists in the "Teams" metadata
    Then "TeamAddress2" MUST be "String" data type
    And "TeamAddress2" length SHOULD be equal to the RESO Suggested Max Length of 50

  @Teams
  Scenario: TeamCarrierRoute
    When "TeamCarrierRoute" exists in the "Teams" metadata
    Then "TeamCarrierRoute" MUST be "String" data type
    And the following synonyms for "TeamCarrierRoute" MUST NOT exist in the metadata
      | RR |
      | CR |
    And "TeamCarrierRoute" length SHOULD be equal to the RESO Suggested Max Length of 9

  @Teams
  Scenario: TeamCity
    When "TeamCity" exists in the "Teams" metadata
    Then "TeamCity" MUST be "String" data type
    And "TeamCity" length SHOULD be equal to the RESO Suggested Max Length of 50

  @Teams
  Scenario: TeamCountry
    When "TeamCountry" exists in the "Teams" metadata
    Then "TeamCountry" MUST be "Single Enumeration" data type
    And "TeamCountry" MAY contain any of the following standard lookups
      | lookupValue | lookupDisplayName |
      | AD | AD |
      | AE | AE |
      | AF | AF |
      | AG | AG |
      | AI | AI |
      | AL | AL |
      | AM | AM |
      | AN | AN |
      | AO | AO |
      | AQ | AQ |
      | AR | AR |
      | AS | AS |
      | AT | AT |
      | AU | AU |
      | AW | AW |
      | AX | AX |
      | AZ | AZ |
      | BA | BA |
      | BB | BB |
      | BD | BD |
      | BE | BE |
      | BF | BF |
      | BG | BG |
      | BH | BH |
      | BI | BI |
      | BJ | BJ |
      | BL | BL |
      | BM | BM |
      | BN | BN |
      | BO | BO |
      | BR | BR |
      | BS | BS |
      | BT | BT |
      | BV | BV |
      | BW | BW |
      | BY | BY |
      | BZ | BZ |
      | CA | CA |
      | CC | CC |
      | CD | CD |
      | CF | CF |
      | CG | CG |
      | CH | CH |
      | CI | CI |
      | CK | CK |
      | CL | CL |
      | CM | CM |
      | CN | CN |
      | CO | CO |
      | CR | CR |
      | CU | CU |
      | CV | CV |
      | CX | CX |
      | CY | CY |
      | CZ | CZ |
      | DE | DE |
      | DJ | DJ |
      | DK | DK |
      | DM | DM |
      | DO | DO |
      | DZ | DZ |
      | EC | EC |
      | EE | EE |
      | EG | EG |
      | EH | EH |
      | ER | ER |
      | ES | ES |
      | ET | ET |
      | FI | FI |
      | FJ | FJ |
      | FK | FK |
      | FM | FM |
      | FO | FO |
      | FR | FR |
      | GA | GA |
      | GB | GB |
      | GD | GD |
      | GE | GE |
      | GF | GF |
      | GG | GG |
      | GH | GH |
      | GI | GI |
      | GL | GL |
      | GM | GM |
      | GN | GN |
      | GP | GP |
      | GQ | GQ |
      | GR | GR |
      | GS | GS |
      | GT | GT |
      | GU | GU |
      | GW | GW |
      | GY | GY |
      | HK | HK |
      | HM | HM |
      | HN | HN |
      | HR | HR |
      | HT | HT |
      | HU | HU |
      | ID | ID |
      | IE | IE |
      | IL | IL |
      | IM | IM |
      | IN | IN |
      | IO | IO |
      | IQ | IQ |
      | IR | IR |
      | IS | IS |
      | IT | IT |
      | JE | JE |
      | JM | JM |
      | JO | JO |
      | JP | JP |
      | KE | KE |
      | KG | KG |
      | KH | KH |
      | KI | KI |
      | KM | KM |
      | KN | KN |
      | KP | KP |
      | KR | KR |
      | KW | KW |
      | KY | KY |
      | KZ | KZ |
      | LA | LA |
      | LB | LB |
      | LC | LC |
      | LI | LI |
      | LK | LK |
      | LR | LR |
      | LS | LS |
      | LT | LT |
      | LU | LU |
      | LV | LV |
      | LY | LY |
      | MA | MA |
      | MC | MC |
      | MD | MD |
      | ME | ME |
      | MF | MF |
      | MG | MG |
      | MH | MH |
      | MK | MK |
      | ML | ML |
      | MM | MM |
      | MN | MN |
      | MO | MO |
      | MP | MP |
      | MQ | MQ |
      | MR | MR |
      | MS | MS |
      | MT | MT |
      | MU | MU |
      | MV | MV |
      | MW | MW |
      | MX | MX |
      | MY | MY |
      | MZ | MZ |
      | NA | NA |
      | NC | NC |
      | NE | NE |
      | NF | NF |
      | NG | NG |
      | NI | NI |
      | NL | NL |
      | NP | NP |
      | NR | NR |
      | NU | NU |
      | NZ | NZ |
      | OM | OM |
      | OT | OT |
      | PA | PA |
      | PE | PE |
      | PF | PF |
      | PG | PG |
      | PH | PH |
      | PK | PK |
      | PL | PL |
      | PM | PM |
      | PN | PN |
      | PR | PR |
      | PS | PS |
      | PT | PT |
      | PW | PW |
      | PY | PY |
      | QA | QA |
      | RE | RE |
      | RO | RO |
      | RS | RS |
      | RU | RU |
      | RW | RW |
      | SA | SA |
      | SB | SB |
      | SC | SC |
      | SD | SD |
      | SE | SE |
      | SG | SG |
      | SH | SH |
      | SI | SI |
      | SJ | SJ |
      | SK | SK |
      | SL | SL |
      | SM | SM |
      | SN | SN |
      | SO | SO |
      | SR | SR |
      | ST | ST |
      | SV | SV |
      | SY | SY |
      | SZ | SZ |
      | TC | TC |
      | TD | TD |
      | TF | TF |
      | TG | TG |
      | TH | TH |
      | TJ | TJ |
      | TK | TK |
      | TL | TL |
      | TM | TM |
      | TN | TN |
      | TO | TO |
      | TR | TR |
      | TT | TT |
      | TV | TV |
      | TW | TW |
      | TZ | TZ |
      | UA | UA |
      | UG | UG |
      | UM | UM |
      | US | US |
      | UY | UY |
      | UZ | UZ |
      | VA | VA |
      | VC | VC |
      | VE | VE |
      | VG | VG |
      | VI | VI |
      | VN | VN |
      | VU | VU |
      | WF | WF |
      | WS | WS |
      | YE | YE |
      | YT | YT |
      | ZA | ZA |
      | ZM | ZM |
      | ZW | ZW |

  @Teams
  Scenario: TeamCountyOrParish
    When "TeamCountyOrParish" exists in the "Teams" metadata
    Then "TeamCountyOrParish" MUST be "Single Enumeration" data type
    And the following synonyms for "TeamCountyOrParish" MUST NOT exist in the metadata
      | County |

  @Teams
  Scenario: TeamDescription
    When "TeamDescription" exists in the "Teams" metadata
    Then "TeamDescription" MUST be "String" data type
    And "TeamDescription" length SHOULD be equal to the RESO Suggested Max Length of 1024

  @Teams
  Scenario: TeamDirectPhone
    When "TeamDirectPhone" exists in the "Teams" metadata
    Then "TeamDirectPhone" MUST be "String" data type
    And "TeamDirectPhone" length SHOULD be equal to the RESO Suggested Max Length of 16

  @Teams
  Scenario: TeamEmail
    When "TeamEmail" exists in the "Teams" metadata
    Then "TeamEmail" MUST be "String" data type
    And "TeamEmail" length SHOULD be equal to the RESO Suggested Max Length of 80

  @Teams
  Scenario: TeamFax
    When "TeamFax" exists in the "Teams" metadata
    Then "TeamFax" MUST be "String" data type
    And "TeamFax" length SHOULD be equal to the RESO Suggested Max Length of 16

  @Teams
  Scenario: TeamKey
    When "TeamKey" exists in the "Teams" metadata
    Then "TeamKey" MUST be "String" data type
    And "TeamKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @Teams
  Scenario: TeamKeyNumeric
    When "TeamKeyNumeric" exists in the "Teams" metadata
    Then "TeamKeyNumeric" MUST be "Integer" data type

  @Teams
  Scenario: TeamLeadKey
    When "TeamLeadKey" exists in the "Teams" metadata
    Then "TeamLeadKey" MUST be "String" data type
    And "TeamLeadKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @Teams
  Scenario: TeamLeadKeyNumeric
    When "TeamLeadKeyNumeric" exists in the "Teams" metadata
    Then "TeamLeadKeyNumeric" MUST be "Integer" data type

  @Teams
  Scenario: TeamLeadLoginId
    When "TeamLeadLoginId" exists in the "Teams" metadata
    Then "TeamLeadLoginId" MUST be "String" data type
    And "TeamLeadLoginId" length SHOULD be equal to the RESO Suggested Max Length of 25

  @Teams
  Scenario: TeamLeadMlsId
    When "TeamLeadMlsId" exists in the "Teams" metadata
    Then "TeamLeadMlsId" MUST be "String" data type
    And "TeamLeadMlsId" length SHOULD be equal to the RESO Suggested Max Length of 25

  @Teams
  Scenario: TeamLeadNationalAssociationId
    When "TeamLeadNationalAssociationId" exists in the "Teams" metadata
    Then "TeamLeadNationalAssociationId" MUST be "String" data type
    And "TeamLeadNationalAssociationId" length SHOULD be equal to the RESO Suggested Max Length of 25

  @Teams
  Scenario: TeamLeadStateLicense
    When "TeamLeadStateLicense" exists in the "Teams" metadata
    Then "TeamLeadStateLicense" MUST be "String" data type
    And "TeamLeadStateLicense" length SHOULD be equal to the RESO Suggested Max Length of 50

  @Teams
  Scenario: TeamLeadStateLicenseState
    When "TeamLeadStateLicenseState" exists in the "Teams" metadata
    Then "TeamLeadStateLicenseState" MUST be "Single Enumeration" data type
    And "TeamLeadStateLicenseState" MAY contain any of the following standard lookups
      | lookupValue | lookupDisplayName |
      | AB | AB |
      | AK | AK |
      | AL | AL |
      | AR | AR |
      | AZ | AZ |
      | BC | BC |
      | CA | CA |
      | CO | CO |
      | CT | CT |
      | DC | DC |
      | DE | DE |
      | FL | FL |
      | GA | GA |
      | HI | HI |
      | IA | IA |
      | ID | ID |
      | IL | IL |
      | IN | IN |
      | KS | KS |
      | KY | KY |
      | LA | LA |
      | MA | MA |
      | MB | MB |
      | MD | MD |
      | ME | ME |
      | MI | MI |
      | MN | MN |
      | MO | MO |
      | MS | MS |
      | MT | MT |
      | NB | NB |
      | NC | NC |
      | ND | ND |
      | NE | NE |
      | NF | NF |
      | NH | NH |
      | NJ | NJ |
      | NM | NM |
      | NS | NS |
      | NT | NT |
      | NU | NU |
      | NV | NV |
      | NY | NY |
      | OH | OH |
      | OK | OK |
      | ON | ON |
      | OR | OR |
      | PA | PA |
      | PE | PE |
      | QC | QC |
      | RI | RI |
      | SC | SC |
      | SD | SD |
      | SK | SK |
      | TN | TN |
      | TX | TX |
      | UT | UT |
      | VA | VA |
      | VI | VI |
      | VT | VT |
      | WA | WA |
      | WI | WI |
      | WV | WV |
      | WY | WY |
      | YT | YT |

  @Teams
  Scenario: TeamMobilePhone
    When "TeamMobilePhone" exists in the "Teams" metadata
    Then "TeamMobilePhone" MUST be "String" data type
    And "TeamMobilePhone" length SHOULD be equal to the RESO Suggested Max Length of 16

  @Teams
  Scenario: TeamName
    When "TeamName" exists in the "Teams" metadata
    Then "TeamName" MUST be "String" data type
    And "TeamName" length SHOULD be equal to the RESO Suggested Max Length of 50

  @Teams
  Scenario: TeamOfficePhone
    When "TeamOfficePhone" exists in the "Teams" metadata
    Then "TeamOfficePhone" MUST be "String" data type
    And "TeamOfficePhone" length SHOULD be equal to the RESO Suggested Max Length of 16

  @Teams
  Scenario: TeamOfficePhoneExt
    When "TeamOfficePhoneExt" exists in the "Teams" metadata
    Then "TeamOfficePhoneExt" MUST be "String" data type
    And "TeamOfficePhoneExt" length SHOULD be equal to the RESO Suggested Max Length of 10

  @Teams
  Scenario: TeamPostalCode
    When "TeamPostalCode" exists in the "Teams" metadata
    Then "TeamPostalCode" MUST be "String" data type
    And "TeamPostalCode" length SHOULD be equal to the RESO Suggested Max Length of 10

  @Teams
  Scenario: TeamPostalCodePlus4
    When "TeamPostalCodePlus4" exists in the "Teams" metadata
    Then "TeamPostalCodePlus4" MUST be "String" data type
    And "TeamPostalCodePlus4" length SHOULD be equal to the RESO Suggested Max Length of 4

  @Teams
  Scenario: TeamPreferredPhone
    When "TeamPreferredPhone" exists in the "Teams" metadata
    Then "TeamPreferredPhone" MUST be "String" data type
    And "TeamPreferredPhone" length SHOULD be equal to the RESO Suggested Max Length of 16

  @Teams
  Scenario: TeamPreferredPhoneExt
    When "TeamPreferredPhoneExt" exists in the "Teams" metadata
    Then "TeamPreferredPhoneExt" MUST be "String" data type
    And "TeamPreferredPhoneExt" length SHOULD be equal to the RESO Suggested Max Length of 10

  @Teams
  Scenario: TeamStateOrProvince
    When "TeamStateOrProvince" exists in the "Teams" metadata
    Then "TeamStateOrProvince" MUST be "Single Enumeration" data type
    And "TeamStateOrProvince" MAY contain any of the following standard lookups
      | lookupValue | lookupDisplayName |
      | AB | AB |
      | AK | AK |
      | AL | AL |
      | AR | AR |
      | AZ | AZ |
      | BC | BC |
      | CA | CA |
      | CO | CO |
      | CT | CT |
      | DC | DC |
      | DE | DE |
      | FL | FL |
      | GA | GA |
      | HI | HI |
      | IA | IA |
      | ID | ID |
      | IL | IL |
      | IN | IN |
      | KS | KS |
      | KY | KY |
      | LA | LA |
      | MA | MA |
      | MB | MB |
      | MD | MD |
      | ME | ME |
      | MI | MI |
      | MN | MN |
      | MO | MO |
      | MS | MS |
      | MT | MT |
      | NB | NB |
      | NC | NC |
      | ND | ND |
      | NE | NE |
      | NF | NF |
      | NH | NH |
      | NJ | NJ |
      | NM | NM |
      | NS | NS |
      | NT | NT |
      | NU | NU |
      | NV | NV |
      | NY | NY |
      | OH | OH |
      | OK | OK |
      | ON | ON |
      | OR | OR |
      | PA | PA |
      | PE | PE |
      | QC | QC |
      | RI | RI |
      | SC | SC |
      | SD | SD |
      | SK | SK |
      | TN | TN |
      | TX | TX |
      | UT | UT |
      | VA | VA |
      | VI | VI |
      | VT | VT |
      | WA | WA |
      | WI | WI |
      | WV | WV |
      | WY | WY |
      | YT | YT |

  @Teams
  Scenario: TeamStatus
    When "TeamStatus" exists in the "Teams" metadata
    Then "TeamStatus" MUST be "Single Enumeration" data type
    And "TeamStatus" MAY contain any of the following standard lookups
      | lookupValue | lookupDisplayName |
      | Active | Active |
      | Inactive | Inactive |

  @Teams
  Scenario: TeamTollFreePhone
    When "TeamTollFreePhone" exists in the "Teams" metadata
    Then "TeamTollFreePhone" MUST be "String" data type
    And "TeamTollFreePhone" length SHOULD be equal to the RESO Suggested Max Length of 16

  @Teams
  Scenario: TeamVoiceMail
    When "TeamVoiceMail" exists in the "Teams" metadata
    Then "TeamVoiceMail" MUST be "String" data type
    And "TeamVoiceMail" length SHOULD be equal to the RESO Suggested Max Length of 16

  @Teams
  Scenario: TeamVoiceMailExt
    When "TeamVoiceMailExt" exists in the "Teams" metadata
    Then "TeamVoiceMailExt" MUST be "String" data type
    And "TeamVoiceMailExt" length SHOULD be equal to the RESO Suggested Max Length of 10
