# This file was autogenerated on: 2024040203565922
Feature: OUID

  Background:
    Given a RESOScript or Metadata file are provided
    When a RESOScript file is provided
    Then Client Settings and Parameters can be read from the RESOScript
    And a test container was successfully created from the given RESOScript file
    And the test container uses an Authorization Code or Client Credentials for authentication
    And valid metadata were retrieved from the server
    When a metadata file is provided
    Then a test container was successfully created from the given metadata file
    And valid metadata are loaded into the test container

  @OUID @dd-2.0
  Scenario: ChangedByMemberID
    Given that the following synonyms for "ChangedByMemberID" DO NOT exist in the "OUID" metadata
      | ChangedByAgentID |
    When "ChangedByMemberID" exists in the "OUID" metadata
    Then "ChangedByMemberID" MUST be "String" data type
    And "ChangedByMemberID" length SHOULD be equal to the RESO Suggested Max Length of 25

  @OUID @dd-2.0
  Scenario: ChangedByMemberKey
    Given that the following synonyms for "ChangedByMemberKey" DO NOT exist in the "OUID" metadata
      | ChangedByAgentKey |
    When "ChangedByMemberKey" exists in the "OUID" metadata
    Then "ChangedByMemberKey" MUST be "String" data type
    And "ChangedByMemberKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OUID @dd-2.0
  Scenario: ModificationTimestamp
    When "ModificationTimestamp" exists in the "OUID" metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type

  @OUID @dd-2.0
  Scenario: OrganizationAddress1
    When "OrganizationAddress1" exists in the "OUID" metadata
    Then "OrganizationAddress1" MUST be "String" data type
    And "OrganizationAddress1" length SHOULD be equal to the RESO Suggested Max Length of 50

  @OUID @dd-2.0
  Scenario: OrganizationAddress2
    When "OrganizationAddress2" exists in the "OUID" metadata
    Then "OrganizationAddress2" MUST be "String" data type
    And "OrganizationAddress2" length SHOULD be equal to the RESO Suggested Max Length of 50

  @OUID @dd-2.0
  Scenario: OrganizationAOR
    When "OrganizationAOR" exists in the "OUID" metadata
    Then "OrganizationAOR" MUST be "Single Enumeration" data type

  @OUID @dd-2.0
  Scenario: OrganizationAorOuid
    When "OrganizationAorOuid" exists in the "OUID" metadata
    Then "OrganizationAorOuid" MUST be "String" data type
    And "OrganizationAorOuid" length SHOULD be equal to the RESO Suggested Max Length of 25

  @OUID @dd-2.0
  Scenario: OrganizationAorOuidKey
    When "OrganizationAorOuidKey" exists in the "OUID" metadata
    Then "OrganizationAorOuidKey" MUST be "String" data type
    And "OrganizationAorOuidKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OUID @dd-2.0
  Scenario: OrganizationCarrierRoute
    Given that the following synonyms for "OrganizationCarrierRoute" DO NOT exist in the "OUID" metadata
      | RR |
      | CR |
    When "OrganizationCarrierRoute" exists in the "OUID" metadata
    Then "OrganizationCarrierRoute" MUST be "String" data type
    And "OrganizationCarrierRoute" length SHOULD be equal to the RESO Suggested Max Length of 9

  @OUID @dd-2.0
  Scenario: OrganizationCity
    When "OrganizationCity" exists in the "OUID" metadata
    Then "OrganizationCity" MUST be "String" data type
    And "OrganizationCity" length SHOULD be equal to the RESO Suggested Max Length of 50

  @OUID @dd-2.0
  Scenario: OrganizationComments
    When "OrganizationComments" exists in the "OUID" metadata
    Then "OrganizationComments" MUST be "String" data type
    And "OrganizationComments" length SHOULD be equal to the RESO Suggested Max Length of 500

  @OUID @dd-2.0
  Scenario: OrganizationContactEmail
    When "OrganizationContactEmail" exists in the "OUID" metadata
    Then "OrganizationContactEmail" MUST be "String" data type
    And "OrganizationContactEmail" length SHOULD be equal to the RESO Suggested Max Length of 80

  @OUID @dd-2.0
  Scenario: OrganizationContactFax
    When "OrganizationContactFax" exists in the "OUID" metadata
    Then "OrganizationContactFax" MUST be "String" data type
    And "OrganizationContactFax" length SHOULD be equal to the RESO Suggested Max Length of 16

  @OUID @dd-2.0
  Scenario: OrganizationContactFirstName
    When "OrganizationContactFirstName" exists in the "OUID" metadata
    Then "OrganizationContactFirstName" MUST be "String" data type
    And "OrganizationContactFirstName" length SHOULD be equal to the RESO Suggested Max Length of 50

  @OUID @dd-2.0
  Scenario: OrganizationContactFullName
    When "OrganizationContactFullName" exists in the "OUID" metadata
    Then "OrganizationContactFullName" MUST be "String" data type
    And "OrganizationContactFullName" length SHOULD be equal to the RESO Suggested Max Length of 150

  @OUID @dd-2.0
  Scenario: OrganizationContactJobTitle
    When "OrganizationContactJobTitle" exists in the "OUID" metadata
    Then "OrganizationContactJobTitle" MUST be "String" data type
    And "OrganizationContactJobTitle" length SHOULD be equal to the RESO Suggested Max Length of 50

  @OUID @dd-2.0
  Scenario: OrganizationContactLastName
    When "OrganizationContactLastName" exists in the "OUID" metadata
    Then "OrganizationContactLastName" MUST be "String" data type
    And "OrganizationContactLastName" length SHOULD be equal to the RESO Suggested Max Length of 50

  @OUID @dd-2.0
  Scenario: OrganizationContactMiddleName
    When "OrganizationContactMiddleName" exists in the "OUID" metadata
    Then "OrganizationContactMiddleName" MUST be "String" data type
    And "OrganizationContactMiddleName" length SHOULD be equal to the RESO Suggested Max Length of 50

  @OUID @dd-2.0
  Scenario: OrganizationContactNamePrefix
    Given that the following synonyms for "OrganizationContactNamePrefix" DO NOT exist in the "OUID" metadata
      | Salutation |
      | Title |
    When "OrganizationContactNamePrefix" exists in the "OUID" metadata
    Then "OrganizationContactNamePrefix" MUST be "String" data type
    And "OrganizationContactNamePrefix" length SHOULD be equal to the RESO Suggested Max Length of 10

  @OUID @dd-2.0
  Scenario: OrganizationContactNameSuffix
    When "OrganizationContactNameSuffix" exists in the "OUID" metadata
    Then "OrganizationContactNameSuffix" MUST be "String" data type
    And "OrganizationContactNameSuffix" length SHOULD be equal to the RESO Suggested Max Length of 10

  @OUID @dd-2.0
  Scenario: OrganizationContactPhone
    When "OrganizationContactPhone" exists in the "OUID" metadata
    Then "OrganizationContactPhone" MUST be "String" data type
    And "OrganizationContactPhone" length SHOULD be equal to the RESO Suggested Max Length of 16

  @OUID @dd-2.0
  Scenario: OrganizationContactPhoneExt
    When "OrganizationContactPhoneExt" exists in the "OUID" metadata
    Then "OrganizationContactPhoneExt" MUST be "String" data type
    And "OrganizationContactPhoneExt" length SHOULD be equal to the RESO Suggested Max Length of 10

  @OUID @dd-2.0
  Scenario: OrganizationCountry
    When "OrganizationCountry" exists in the "OUID" metadata
    Then "OrganizationCountry" MUST be "Single Enumeration" data type

  @OUID @dd-2.0
  Scenario: OrganizationCountyOrParish
    Given that the following synonyms for "OrganizationCountyOrParish" DO NOT exist in the "OUID" metadata
      | County |
    When "OrganizationCountyOrParish" exists in the "OUID" metadata
    Then "OrganizationCountyOrParish" MUST be "Single Enumeration" data type

  @OUID @dd-2.0
  Scenario: OrganizationMemberCount
    Given that the following synonyms for "OrganizationMemberCount" DO NOT exist in the "OUID" metadata
      | OrganizationAgentCount |
    When "OrganizationMemberCount" exists in the "OUID" metadata
    Then "OrganizationMemberCount" MUST be "Integer" data type

  @OUID @dd-2.0
  Scenario: OrganizationMlsCode
    When "OrganizationMlsCode" exists in the "OUID" metadata
    Then "OrganizationMlsCode" MUST be "String" data type
    And "OrganizationMlsCode" length SHOULD be equal to the RESO Suggested Max Length of 25

  @OUID @dd-2.0
  Scenario: OrganizationMlsVendorName
    When "OrganizationMlsVendorName" exists in the "OUID" metadata
    Then "OrganizationMlsVendorName" MUST be "String" data type
    And "OrganizationMlsVendorName" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OUID @dd-2.0
  Scenario: OrganizationMlsVendorOuid
    When "OrganizationMlsVendorOuid" exists in the "OUID" metadata
    Then "OrganizationMlsVendorOuid" MUST be "String" data type
    And "OrganizationMlsVendorOuid" length SHOULD be equal to the RESO Suggested Max Length of 25

  @OUID @dd-2.0
  Scenario: OrganizationName
    When "OrganizationName" exists in the "OUID" metadata
    Then "OrganizationName" MUST be "String" data type
    And "OrganizationName" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OUID @dd-2.0
  Scenario: OrganizationNationalAssociationId
    When "OrganizationNationalAssociationId" exists in the "OUID" metadata
    Then "OrganizationNationalAssociationId" MUST be "String" data type
    And "OrganizationNationalAssociationId" length SHOULD be equal to the RESO Suggested Max Length of 25

  @OUID @dd-2.0
  Scenario: OrganizationPostalCode
    When "OrganizationPostalCode" exists in the "OUID" metadata
    Then "OrganizationPostalCode" MUST be "String" data type
    And "OrganizationPostalCode" length SHOULD be equal to the RESO Suggested Max Length of 10

  @OUID @dd-2.0
  Scenario: OrganizationPostalCodePlus4
    When "OrganizationPostalCodePlus4" exists in the "OUID" metadata
    Then "OrganizationPostalCodePlus4" MUST be "String" data type
    And "OrganizationPostalCodePlus4" length SHOULD be equal to the RESO Suggested Max Length of 4

  @OUID @dd-2.0
  Scenario: OrganizationSocialMediaType
    When "OrganizationSocialMediaType" exists in the "OUID" metadata
    Then "OrganizationSocialMediaType" MUST be "Single Enumeration" data type

  @OUID @dd-2.0
  Scenario: OrganizationStateLicense
    When "OrganizationStateLicense" exists in the "OUID" metadata
    Then "OrganizationStateLicense" MUST be "String" data type
    And "OrganizationStateLicense" length SHOULD be equal to the RESO Suggested Max Length of 50

  @OUID @dd-2.0
  Scenario: OrganizationStateLicenseState
    When "OrganizationStateLicenseState" exists in the "OUID" metadata
    Then "OrganizationStateLicenseState" MUST be "Single Enumeration" data type

  @OUID @dd-2.0
  Scenario: OrganizationStateOrProvince
    When "OrganizationStateOrProvince" exists in the "OUID" metadata
    Then "OrganizationStateOrProvince" MUST be "Single Enumeration" data type

  @OUID @dd-2.0
  Scenario: OrganizationStatus
    When "OrganizationStatus" exists in the "OUID" metadata
    Then "OrganizationStatus" MUST be "Boolean" data type

  @OUID @dd-2.0
  Scenario: OrganizationStatusChangeTimestamp
    When "OrganizationStatusChangeTimestamp" exists in the "OUID" metadata
    Then "OrganizationStatusChangeTimestamp" MUST be "Timestamp" data type

  @OUID @dd-2.0
  Scenario: OrganizationType
    When "OrganizationType" exists in the "OUID" metadata
    Then "OrganizationType" MUST be "Single Enumeration" data type

  @OUID @dd-2.0
  Scenario: OrganizationUniqueId
    When "OrganizationUniqueId" exists in the "OUID" metadata
    Then "OrganizationUniqueId" MUST be "String" data type
    And "OrganizationUniqueId" length SHOULD be equal to the RESO Suggested Max Length of 25

  @OUID @dd-2.0
  Scenario: OrganizationUniqueIdKey
    When "OrganizationUniqueIdKey" exists in the "OUID" metadata
    Then "OrganizationUniqueIdKey" MUST be "String" data type
    And "OrganizationUniqueIdKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @OUID @dd-2.0
  Scenario: OriginalEntryTimestamp
    When "OriginalEntryTimestamp" exists in the "OUID" metadata
    Then "OriginalEntryTimestamp" MUST be "Timestamp" data type
