# This file was autogenerated on: 20211212171220893
Feature: PropertyGreenVerification

  Background:
    Given a RESOScript or Metadata file are provided
    When a RESOScript file is provided
    Then Client Settings and Parameters can be read from the RESOScript
    And a test container was successfully created from the given RESOScript file
    And the test container uses an Authorization Code or Client Credentials for authentication
    And valid metadata were retrieved from the server
    When a metadata file is provided
    Then a test container was successfully created from the given metadata file
    And valid metadata are loaded into the test container

  @PropertyGreenVerification @IDX
  Scenario: GreenBuildingVerificationKey
    When "GreenBuildingVerificationKey" exists in the "PropertyGreenVerification" metadata
    Then "GreenBuildingVerificationKey" MUST be "String" data type
    And "GreenBuildingVerificationKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @PropertyGreenVerification @IDX
  Scenario: GreenBuildingVerificationKeyNumeric
    When "GreenBuildingVerificationKeyNumeric" exists in the "PropertyGreenVerification" metadata
    Then "GreenBuildingVerificationKeyNumeric" MUST be "Integer" data type

  @PropertyGreenVerification @IDX
  Scenario: GreenBuildingVerificationType
    Given that the following synonyms for "GreenBuildingVerificationType" DO NOT exist in the "PropertyGreenVerification" metadata
      | GreenBuildingCertification |
      | GreenBuildingVerification |
      | GreenBuildingRating |
    When "GreenBuildingVerificationType" exists in the "PropertyGreenVerification" metadata
    Then "GreenBuildingVerificationType" MUST be "Single Enumeration" data type

  @PropertyGreenVerification @IDX
  Scenario: GreenVerificationBody
    Given that the following synonyms for "GreenVerificationBody" DO NOT exist in the "PropertyGreenVerification" metadata
      | GreenCertifyingBody |
      | GreenRatingBody |
    When "GreenVerificationBody" exists in the "PropertyGreenVerification" metadata
    Then "GreenVerificationBody" MUST be "String" data type
    And "GreenVerificationBody" length SHOULD be equal to the RESO Suggested Max Length of 50

  @PropertyGreenVerification @IDX
  Scenario: GreenVerificationMetric
    Given that the following synonyms for "GreenVerificationMetric" DO NOT exist in the "PropertyGreenVerification" metadata
      | GreenCertificationMetric |
      | GreenRatingMetric |
    When "GreenVerificationMetric" exists in the "PropertyGreenVerification" metadata
    Then "GreenVerificationMetric" MUST be "Integer" data type

  @PropertyGreenVerification @IDX
  Scenario: GreenVerificationRating
    Given that the following synonyms for "GreenVerificationRating" DO NOT exist in the "PropertyGreenVerification" metadata
      | GreenCertificationRating |
      | GreenRating |
    When "GreenVerificationRating" exists in the "PropertyGreenVerification" metadata
    Then "GreenVerificationRating" MUST be "String" data type
    And "GreenVerificationRating" length SHOULD be equal to the RESO Suggested Max Length of 50

  @PropertyGreenVerification @IDX
  Scenario: GreenVerificationSource
    Given that the following synonyms for "GreenVerificationSource" DO NOT exist in the "PropertyGreenVerification" metadata
      | GreenRatingSource |
      | GreenCertificationSource |
    When "GreenVerificationSource" exists in the "PropertyGreenVerification" metadata
    Then "GreenVerificationSource" MUST be "Single Enumeration" data type

  @PropertyGreenVerification @IDX
  Scenario: GreenVerificationStatus
    Given that the following synonyms for "GreenVerificationStatus" DO NOT exist in the "PropertyGreenVerification" metadata
      | GreenRatingStatus |
      | GreenCertificationStatus |
    When "GreenVerificationStatus" exists in the "PropertyGreenVerification" metadata
    Then "GreenVerificationStatus" MUST be "Single Enumeration" data type

  @PropertyGreenVerification @IDX
  Scenario: GreenVerificationURL
    Given that the following synonyms for "GreenVerificationURL" DO NOT exist in the "PropertyGreenVerification" metadata
      | GreenRatingURL |
      | GreenCertificationURL |
    When "GreenVerificationURL" exists in the "PropertyGreenVerification" metadata
    Then "GreenVerificationURL" MUST be "String" data type
    And "GreenVerificationURL" length SHOULD be equal to the RESO Suggested Max Length of 8000

  @PropertyGreenVerification @IDX
  Scenario: GreenVerificationVersion
    Given that the following synonyms for "GreenVerificationVersion" DO NOT exist in the "PropertyGreenVerification" metadata
      | GreenRatingVersion |
      | GreenCertificationVersion |
    When "GreenVerificationVersion" exists in the "PropertyGreenVerification" metadata
    Then "GreenVerificationVersion" MUST be "String" data type
    And "GreenVerificationVersion" length SHOULD be equal to the RESO Suggested Max Length of 25

  @PropertyGreenVerification @IDX
  Scenario: GreenVerificationYear
    Given that the following synonyms for "GreenVerificationYear" DO NOT exist in the "PropertyGreenVerification" metadata
      | GreenYearCertified |
      | GreenRatingYear |
    When "GreenVerificationYear" exists in the "PropertyGreenVerification" metadata
    Then "GreenVerificationYear" MUST be "Integer" data type

  @PropertyGreenVerification @IDX
  Scenario: ListingId
    Given that the following synonyms for "ListingId" DO NOT exist in the "PropertyGreenVerification" metadata
      | MLNumber |
      | MLSNumber |
      | ListingNumber |
    When "ListingId" exists in the "PropertyGreenVerification" metadata
    Then "ListingId" MUST be "String" data type
    And "ListingId" length SHOULD be equal to the RESO Suggested Max Length of 255

  @PropertyGreenVerification @IDX
  Scenario: ListingKey
    Given that the following synonyms for "ListingKey" DO NOT exist in the "PropertyGreenVerification" metadata
      | SystemUniqueID |
      | ImmediateSourceID |
    When "ListingKey" exists in the "PropertyGreenVerification" metadata
    Then "ListingKey" MUST be "String" data type
    And "ListingKey" length SHOULD be equal to the RESO Suggested Max Length of 255

  @PropertyGreenVerification @IDX
  Scenario: ListingKeyNumeric
    Given that the following synonyms for "ListingKeyNumeric" DO NOT exist in the "PropertyGreenVerification" metadata
      | SystemUniqueID |
      | ImmediateSourceID |
    When "ListingKeyNumeric" exists in the "PropertyGreenVerification" metadata
    Then "ListingKeyNumeric" MUST be "Integer" data type

  @PropertyGreenVerification @IDX
  Scenario: ModificationTimestamp
    When "ModificationTimestamp" exists in the "PropertyGreenVerification" metadata
    Then "ModificationTimestamp" MUST be "Timestamp" data type
