package org.reso.certification.generators;

import org.apache.logging.log4j.LogManager;
import org.apache.logging.log4j.Logger;
import org.apache.poi.ss.usermodel.Sheet;
import org.reso.commander.common.Utils;
import org.reso.models.DataDictionaryRow;

import java.util.Arrays;
import java.util.Date;
import java.util.stream.Collectors;

import static org.reso.certification.containers.WebAPITestContainer.SINGLE_SPACE;
import static org.reso.certification.generators.DataDictionaryGenerator.createFile;

public class BDDProcessor extends WorksheetProcessor {
  private static final Logger LOG = LogManager.getLogger(BDDProcessor.class);

  Sheet sheet;

  @Override
  public void processSheet(Sheet sheet) {
    this.sheet = sheet;
    markup.append(BDDTemplates.buildHeaderInfo(sheet.getSheetName(), startTimestamp));
  }

  @Override
  void processNumber() {
    markup.append(BDDTemplates.buildNumberTest(dictionaryRow, sheet.getSheetName()));
  }

  @Override
  void processStringListSingle() {
    markup.append(BDDTemplates.buildStringListSingleTest(dictionaryRow, sheet.getSheetName()));
  }

  @Override
  void processString() {
    markup.append(BDDTemplates.buildStringTest(dictionaryRow, sheet.getSheetName()));
  }

  @Override
  void processBoolean() {
    markup.append(BDDTemplates.buildBooleanTest(dictionaryRow, sheet.getSheetName()));
  }

  @Override
  void processStringListMulti() {
    markup.append(BDDTemplates.buildStringListMultiTest(dictionaryRow, sheet.getSheetName()));
  }

  @Override
  void processDate() {
    markup.append(BDDTemplates.buildDateTest(dictionaryRow, sheet.getSheetName()));
  }

  @Override
  void processTimestamp() {
    markup.append(BDDTemplates.buildTimestampTest(dictionaryRow, sheet.getSheetName()));
  }

  @Override
  void processCollection() {
    LOG.debug("Collection Type is not supported!");
  }

  @Override
  void generateOutput() {
    LOG.info("Generating BDD .feature files for the following resources: " + resourceTemplates.keySet().toString());
    resourceTemplates.forEach((resourceName, content) -> {
      //put in local directory rather than relative to where the input file is
      createFile(getDirectoryName(), resourceName.toLowerCase() + ".feature", content);
    });
  }

  public static final class BDDTemplates {
    /**
     * Contains various templates used for test generation
     */
    public static String buildHeaderInfo(String content, String generatedTimestamp) {
      if (content == null) return null;
      if (generatedTimestamp == null) generatedTimestamp = Utils.getTimestamp(new Date());
      return
        "# This file was autogenerated on: " + generatedTimestamp + "\n" +
        "Feature: " + content + "\n\n" +
        "  Background:\n" +
        "    Given a RESOScript file was provided\n" +
        "    And Client Settings and Parameters were read from the file\n" +
        "    And a test container was successfully created from the given RESOScript\n" +
        "    And the test container uses an Authorization Code or Client Credentials for authentication\n" +
        "    And metadata were retrieved from the server\n" +
        "    And metadata are valid\n";
    }

    public static String buildBooleanTest(DataDictionaryRow row, String... tags) {
      if (row == null) return null;
      return
        "\n  @" + row.getStandardName() + SINGLE_SPACE +
            Arrays.stream(tags).map(tag -> "@" + tag).collect(Collectors.joining(SINGLE_SPACE)) + "\n" +
          "  Scenario: " + row.getStandardName() + "\n" +
          "    Given \"" + row.getStandardName() + "\" exists in the metadata\n" +
          "    And \"" + row.getStandardName() + "\" is not a synonym for another field\n" +
          "    Then \"" + row.getStandardName() + "\" MUST be \"Boolean\" data type\n";
    }

    public static String buildDateTest(DataDictionaryRow row, String... tags) {
      if (row == null) return null;
      String template =
        "\n  @" + row.getStandardName() + SINGLE_SPACE +
            Arrays.stream(tags).map(tag -> "@" + tag).collect(Collectors.joining(SINGLE_SPACE)) + "\n" +
          "  Scenario: " + row.getStandardName() + "\n" +
          "    Given \"" + row.getStandardName() + "\" exists in the metadata\n" +
          "    Then \"" + row.getStandardName() + "\" MUST be \"Date\" data type\n";

      if (row.getSuggestedMaxLength() != null)
        template +=
          "    And \"" + row.getStandardName() + "\" length SHOULD be less than or equal to the RESO Suggested Max Length of " + row.getSuggestedMaxLength() + "\n";

      return template;
    }

    public static String buildNumberTest(DataDictionaryRow row, String... tags) {
      if (row == null) return null;

      if (row.getSuggestedMaxPrecision() != null) return buildDecimalTest(row, tags);
      else return buildIntegerTest(row, tags);
    }

    public static String buildDecimalTest(DataDictionaryRow row, String... tags) {
      if (row == null) return null;
      String template =
        "\n  @" + row.getStandardName() + SINGLE_SPACE +
            Arrays.stream(tags).map(tag -> "@" + tag).collect(Collectors.joining(SINGLE_SPACE)) + "\n" +
          "  Scenario: " + row.getStandardName() + "\n" +
          "    Given \"" + row.getStandardName() + "\" exists in the metadata\n" +
          "    Then \"" + row.getStandardName() + "\" MUST be \"Decimal\" data type\n";

      if (row.getSuggestedMaxLength() != null)
        template +=
          "    And \"" + row.getStandardName() + "\" precision SHOULD be less than or equal to the RESO Suggested Max Length of " + row.getSuggestedMaxLength() + "\n";

      if (row.getSuggestedMaxPrecision() != null)
        template +=
          "    And \"" + row.getStandardName() + "\" scale SHOULD be less than or equal to the RESO Suggested Max Scale of " + row.getSuggestedMaxPrecision() + "\n";

      return template;
    }

    public static String buildIntegerTest(DataDictionaryRow row, String... tags) {
      if (row == null) return null;
      return
        "\n  @" + row.getStandardName() + SINGLE_SPACE +
            Arrays.stream(tags).map(tag -> "@" + tag).collect(Collectors.joining(SINGLE_SPACE)) + "\n" +
          "  Scenario: " + row.getStandardName() + "\n" +
          "    Given \"" + row.getStandardName() + "\" exists in the metadata\n" +
          "    Then \"" + row.getStandardName() + "\" MUST be \"Integer\" data type\n";
    }

    public static String buildStringListMultiTest(DataDictionaryRow row, String... tags) {
      if (row == null) return null;
      String template =
        "\n  @" + row.getStandardName() + SINGLE_SPACE +
            Arrays.stream(tags).map(tag -> "@" + tag).collect(Collectors.joining(SINGLE_SPACE)) + "\n" +
          "  Scenario: " + row.getStandardName() + "\n" +
          "    Given \"" + row.getStandardName() + "\" exists in the metadata\n" +
          "    And \"" + row.getStandardName() + "\" enum values exist in the metadata\n" +
          "    And \"" + row.getStandardName() + "\" enum types MUST have at least one member\n" +
          "    Then \"" + row.getStandardName() + "\" MUST be \"String Array\" data type\n";
      if (row.getSuggestedMaxLength() != null)
        template +=
          "    And \"" + row.getStandardName() + "\" SHOULD have no more than the RESO Suggested Max Length of " + row.getSuggestedMaxLength() + " item(s)\n";

      return template;
    }

    public static String buildStringListSingleTest(DataDictionaryRow row, String... tags) {
      if (row == null) return null;
      String template =
        "\n  @" + row.getStandardName() + SINGLE_SPACE +
            Arrays.stream(tags).map(tag -> "@" + tag).collect(Collectors.joining(SINGLE_SPACE)) + "\n" +
          "  Scenario: " + row.getStandardName() + "\n" +
          "    Given \"" + row.getStandardName() + "\" exists in the metadata\n" +
          "    And \"" + row.getStandardName() + "\" enum values exist in the metadata\n" +
          "    And \"" + row.getStandardName() + "\" enum types MUST have exactly one member\n" +
          "    Then \"" + row.getStandardName() + "\" MUST be \"String\" data type\n" +
          "    And \"" + row.getStandardName() + "\" MUST only contain enum values found in the metadata\n";

      if (row.getSuggestedMaxLength() != null)
        template +=
          "    And \"" + row.getStandardName() + "\" length SHOULD be less than or equal to the RESO Suggested Max Length of " + row.getSuggestedMaxLength() + "\n";

      return template;
    }

    public static String buildStringTest(DataDictionaryRow row, String... tags) {
      if (row == null) return null;
      String template =
        "\n  @" + row.getStandardName() + SINGLE_SPACE +
            Arrays.stream(tags).map(tag -> "@" + tag).collect(Collectors.joining(SINGLE_SPACE)) + "\n" +
          "  Scenario: " + row.getStandardName() + "\n" +
          "    Given \"" + row.getStandardName() + "\" exists in the metadata\n" +
          "    Then \"" + row.getStandardName() + "\" MUST be \"String\" data type\n";

      if (row.getSuggestedMaxLength() != null)
        template +=
          "    And \"" + row.getStandardName() + "\" length SHOULD be less than or equal to the RESO Suggested Max Length of " + row.getSuggestedMaxLength() + "\n";

      return template;
    }

    public static String buildTimestampTest(DataDictionaryRow row, String... tags) {
      if (row == null) return null;
      String template =
        "\n  @" + row.getStandardName() + SINGLE_SPACE +
            Arrays.stream(tags).map(tag -> "@" + tag).collect(Collectors.joining(SINGLE_SPACE)) + "\n" +
          "  Scenario: " + row.getStandardName() + "\n" +
          "    Given \"" + row.getStandardName() + "\" exists in the metadata\n" +
          "    Then \"" + row.getStandardName() + "\" MUST be \"Timestamp\" data type\n";

      if (row.getSuggestedMaxLength() != null)
        template +=
          "    And \"" + row.getStandardName() + "\" length SHOULD be less than or equal to the RESO Suggested Max Length of " + row.getSuggestedMaxLength() + "\n";

      return template;
    }
  }
}
